# Compiler and flags
CC = gcc

# Homebrew detection (works on macOS Intel and Apple Silicon). If brew isn't available, these vars stay empty.
HOMEBREW_PREFIX ?= $(shell /opt/homebrew/bin/brew --prefix 2>/dev/null || brew --prefix 2>/dev/null)

# Fallback to common Homebrew locations if brew command fails
ifeq ($(HOMEBREW_PREFIX),)
    ifneq ($(wildcard /opt/homebrew),)
        HOMEBREW_PREFIX = /opt/homebrew
    else ifneq ($(wildcard /usr/local),)
        HOMEBREW_PREFIX = /usr/local
    endif
endif

# Third-party include and lib paths (GMP and OpenSSL via Homebrew)
BREW_INC = $(HOMEBREW_PREFIX)/include
BREW_LIB = $(HOMEBREW_PREFIX)/lib
OPENSSL_INC = $(HOMEBREW_PREFIX)/opt/openssl@3/include
OPENSSL_LIB = $(HOMEBREW_PREFIX)/opt/openssl@3/lib

# Preprocessor flags
CPPFLAGS = -I$(INCLUDE_DIR) -DENABLE_LOGGING \
		   $(if $(HOMEBREW_PREFIX),-I$(BREW_INC)) \
		   $(if $(HOMEBREW_PREFIX),-I$(OPENSSL_INC)) # Include project + Homebrew headers

# Compiler flags
COMMON_FLAGS = -Wall -Wextra -Wshadow -Wformat=2 -Wpedantic -MMD -MP # Common flags for the compiler to enable warnings and generate dependency files
CFLAGS = -O3 -flto $(COMMON_FLAGS) -g # Optimization level 3, link-time optimization, debug information.

# Linker flags
LDFLAGS = $(if $(HOMEBREW_PREFIX),-L$(BREW_LIB)) \
		  $(if $(HOMEBREW_PREFIX),-L$(OPENSSL_LIB)) \
		  -lgmp -lssl -lcrypto -lprimesieve -pthread


# Directories
SRC_DIR = src
OBJ_DIR = build
OBJ_SRC_DIR = $(OBJ_DIR)/src
OBJ_TEST_DIR = $(OBJ_DIR)/test
INCLUDE_DIR = include
OUTPUT_DIR = output
TEST_DIR = test
LOG_DIR = logs

# File for printf stdout
STDOUT_FILE = stdout.txt  # The file where stdout from the program will be saved

# Program name and target
PROGRAM = iZ  # The name of the final program binary
TARGET = $(OBJ_SRC_DIR)/$(PROGRAM)  # The target binary to be built in the build/src directory

# Source and object files
SOURCES = $(shell find $(SRC_DIR) -name "*.c")  # List all .c files in the source directory
OBJECTS = $(patsubst $(SRC_DIR)/%.c, $(OBJ_SRC_DIR)/%.o, $(SOURCES))  # Convert the list of .c files to a list of .o files in the build/src directory

# Test source and object files (excluding main.o)
TEST_SOURCES = $(wildcard $(TEST_DIR)/*.c)  # List all .c files in the test directory
TEST_OBJECTS = $(patsubst $(TEST_DIR)/%.c, $(OBJ_TEST_DIR)/%.o, $(TEST_SOURCES))  # Convert the list of .c files to .o files in the build/test directory
TEST_BUILD_OBJECTS = $(filter-out $(OBJ_SRC_DIR)/main.o, $(OBJECTS)) $(TEST_OBJECTS)  # Test build objects excluding the main.o

# Dependency files
DEPS = $(OBJECTS:.o=.d) $(TEST_OBJECTS:.o=.d)  # List of dependency files (automatically generated by the compiler)

# Output file
OUTPUT = $(OUTPUT_DIR)/$(STDOUT_FILE)  # The final output file where stdout is stored

# Default target
all: directories $(TARGET) run

# Create necessary directories
directories:
	@mkdir -p $(OBJ_SRC_DIR) $(OBJ_TEST_DIR) $(OUTPUT_DIR) $(LOG_DIR) # Create build/, build/src/, build/test/, output/, and logs/ directories

# Build the program
$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(TARGET) $(OBJECTS) $(LDFLAGS)

# Compile source files into object files and mirror the folder structure in build/src
$(OBJ_SRC_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)  # Create the necessary directory structure in build/src
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

# Compile test files into object files and mirror the folder structure in build/test
$(OBJ_TEST_DIR)/%.o: $(TEST_DIR)/%.c
	@mkdir -p $(dir $@)  # Create the necessary directory structure for test objects in build/test
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

# Include dependency files
-include $(DEPS)

# Run the program and save the output
run: $(TARGET)
	@mkdir -p $(OUTPUT_DIR)
	./$(TARGET) >> $(OUTPUT) 2>&1

# New test framework targets
NEW_TEST_DIR = test
# Include test_all.c and individual test files, but exclude any legacy tests.c
NEW_TEST_SOURCES = $(shell find $(NEW_TEST_DIR) -name "*.c" ! -name "tests.c")
NEW_TEST_OBJECTS = $(patsubst $(NEW_TEST_DIR)/%.c, $(OBJ_DIR)/$(NEW_TEST_DIR)/%.o, $(NEW_TEST_SOURCES))
# Exclude main.o from source objects since test_all.c provides main()
NEW_TEST_BUILD_OBJECTS = $(filter-out $(OBJ_SRC_DIR)/main.o, $(OBJECTS)) $(NEW_TEST_OBJECTS)

# Compile new test files
$(OBJ_DIR)/$(NEW_TEST_DIR)/%.o: $(NEW_TEST_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

# Build and run new test framework
test-all: directories $(NEW_TEST_BUILD_OBJECTS)
	@mkdir -p $(OBJ_DIR)/$(NEW_TEST_DIR)
	@echo "Building test runner..."
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(OBJ_DIR)/$(NEW_TEST_DIR)/test_runner $(NEW_TEST_BUILD_OBJECTS) $(LDFLAGS)
	@echo "Running tests..."
	./$(OBJ_DIR)/$(NEW_TEST_DIR)/test_runner

# Run only unit tests
test-unit: directories $(NEW_TEST_BUILD_OBJECTS)
	@mkdir -p $(OBJ_DIR)/$(NEW_TEST_DIR)
	@echo "Building test runner..."
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(OBJ_DIR)/$(NEW_TEST_DIR)/test_runner $(NEW_TEST_BUILD_OBJECTS) $(LDFLAGS)
	@echo "Running unit tests..."
	./$(OBJ_DIR)/$(NEW_TEST_DIR)/test_runner --unit

# Run only integration tests
test-integration: directories $(NEW_TEST_BUILD_OBJECTS)
	@mkdir -p $(OBJ_DIR)/$(NEW_TEST_DIR)
	@echo "Building test runner..."
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(OBJ_DIR)/$(NEW_TEST_DIR)/test_runner $(NEW_TEST_BUILD_OBJECTS) $(LDFLAGS)
	@echo "Running integration tests..."
	./$(OBJ_DIR)/$(NEW_TEST_DIR)/test_runner --integration

# Run only benchmark tests (with safety check)
test-benchmark: directories $(NEW_TEST_BUILD_OBJECTS)
	@mkdir -p $(OBJ_DIR)/$(NEW_TEST_DIR)
	@echo "Building test runner..."
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(OBJ_DIR)/$(NEW_TEST_DIR)/test_runner $(NEW_TEST_BUILD_OBJECTS) $(LDFLAGS)
	@echo "Running benchmark tests..."
	@echo "Warning: Benchmark tests may take time and could have memory issues"
	./$(OBJ_DIR)/$(NEW_TEST_DIR)/test_runner --benchmark

# Legacy test support (backward compatibility)
test: directories $(TEST_OBJECTS) $(TEST_BUILD_OBJECTS)
	@mkdir -p $(OBJ_TEST_DIR)
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(OBJ_TEST_DIR)/test_runner $(TEST_BUILD_OBJECTS) $(LDFLAGS)
	./$(OBJ_TEST_DIR)/test_runner

# Clean generated files
clean:
	rm -rf $(OBJ_DIR) $(OUTPUT_DIR) $(LOG_DIR)

# Build with debug flags
debug: CPPFLAGS += -DENABLE_LOGGING
debug: CFLAGS = -O0 -g $(COMMON_FLAGS)
debug: $(TARGET)

# Build optimized release version without logging
release: CPPFLAGS = -I$(INCLUDE_DIR)
release: CFLAGS = -O3 -flto
release: $(TARGET)

# Help message
help:
	@echo "=========================================="
	@echo "  iZ Project Build System"
	@echo "=========================================="
	@echo "Main targets:"
	@echo "  all             - Build the main program and run it"
	@echo "  run             - Run the main program (builds if needed)"
	@echo "  clean           - Remove all generated files"
	@echo ""
	@echo "Test targets:"
	@echo "  test-all        - Run all tests (recommended)"
	@echo "  test-unit       - Run only unit tests"
	@echo "  test-integration- Run only integration tests"  
	@echo "  test-benchmark  - Run only benchmark tests"
	@echo "  test            - Run legacy tests (deprecated)"
	@echo ""
	@echo "Build variants:"
	@echo "  debug           - Build with debug flags and logging"
	@echo "  release         - Build optimized release version"
	@echo ""
	@echo "Utility:"
	@echo "  help            - Show this help message"
	@echo ""
	@echo "Examples:"
	@echo "  make              # Build and run main program"
	@echo "  make test-all     # Run all tests"
	@echo "  make test-unit    # Run just unit tests"
	@echo "  make clean        # Clean build artifacts"
	@echo "=========================================="

# Phony targets
.PHONY: all run test test-all test-unit test-integration test-benchmark clean debug release help directories

# Delete incomplete files if a command fails
.DELETE_ON_ERROR:
