# Compiler and flags
CC = gcc

# Prefer pkg-config for portability (Linux, macOS Homebrew, etc.)
USE_PKG_CONFIG ?= 1
PKG_CONFIG ?= pkg-config

# Homebrew detection (works on macOS Intel and Apple Silicon). If brew isn't available, these vars stay empty.
HOMEBREW_PREFIX ?= $(shell /opt/homebrew/bin/brew --prefix 2>/dev/null || brew --prefix 2>/dev/null)

# Fallback to common Homebrew locations if brew command fails
ifeq ($(HOMEBREW_PREFIX),)
    ifneq ($(wildcard /opt/homebrew),)
        HOMEBREW_PREFIX = /opt/homebrew
    else ifneq ($(wildcard /usr/local),)
        HOMEBREW_PREFIX = /usr/local
    endif
endif

# Third-party include and lib paths (GMP and OpenSSL via Homebrew)
BREW_INC = $(HOMEBREW_PREFIX)/include
BREW_LIB = $(HOMEBREW_PREFIX)/lib
OPENSSL_INC = $(HOMEBREW_PREFIX)/opt/openssl@3/include
OPENSSL_LIB = $(HOMEBREW_PREFIX)/opt/openssl@3/lib

# Build options
LOGGING ?= 1
THREAD_FLAGS ?= -pthread

# Third-party flags resolved via pkg-config (preferred) or fallbacks
THIRD_PARTY_CFLAGS =
THIRD_PARTY_LDFLAGS =
THIRD_PARTY_LDLIBS =

ifeq ($(USE_PKG_CONFIG),1)
PKG_CONFIG_OK := $(shell command -v $(PKG_CONFIG) >/dev/null 2>&1 && echo 1)
ifeq ($(PKG_CONFIG_OK),1)
PKG_OPENSSL_OK := $(shell $(PKG_CONFIG) --exists openssl >/dev/null 2>&1 && echo 1)
PKG_LIBSSL_OK := $(shell $(PKG_CONFIG) --exists libssl libcrypto >/dev/null 2>&1 && echo 1)
ifeq ($(PKG_OPENSSL_OK),1)
OPENSSL_PC = openssl
else ifeq ($(PKG_LIBSSL_OK),1)
OPENSSL_PC = libssl libcrypto
else
OPENSSL_PC =
endif

PKG_DEPS_OK := $(shell $(PKG_CONFIG) --exists gmp $(OPENSSL_PC) >/dev/null 2>&1 && echo 1)
ifeq ($(PKG_DEPS_OK),1)
THIRD_PARTY_CFLAGS += $(shell $(PKG_CONFIG) --cflags gmp $(OPENSSL_PC))
THIRD_PARTY_LDLIBS += $(shell $(PKG_CONFIG) --libs gmp $(OPENSSL_PC))
endif
endif
endif

# Fallback: Homebrew locations (macOS) + generic link flags
ifeq ($(strip $(THIRD_PARTY_LDLIBS)),)
THIRD_PARTY_CFLAGS += $(if $(HOMEBREW_PREFIX),-I$(BREW_INC)) \
			      $(if $(HOMEBREW_PREFIX),-I$(OPENSSL_INC))
THIRD_PARTY_LDFLAGS += $(if $(HOMEBREW_PREFIX),-L$(BREW_LIB)) \
			       $(if $(HOMEBREW_PREFIX),-L$(OPENSSL_LIB))
THIRD_PARTY_LDLIBS += -lgmp -lssl -lcrypto
endif

# Preprocessor flags
CPPFLAGS = -I$(INCLUDE_DIR) $(if $(filter 1,$(LOGGING)),-DENABLE_LOGGING,) $(THIRD_PARTY_CFLAGS)

# Compiler flags
COMMON_FLAGS = -Wall -Wextra -Wshadow -Wformat=2 -Wpedantic -MMD -MP # Common flags for the compiler to enable warnings and generate dependency files
CFLAGS_OPT ?= -O3 -flto
CFLAGS_DBG ?= -g
CFLAGS = $(CFLAGS_OPT) $(COMMON_FLAGS) $(CFLAGS_DBG) $(THREAD_FLAGS)

# Linker flags (LDFLAGS for -L/-Wl, LDLIBS for -l...)
LDFLAGS = $(THIRD_PARTY_LDFLAGS)
LDLIBS = $(THIRD_PARTY_LDLIBS) $(THREAD_FLAGS)


# Directories
SRC_DIR = src
OBJ_DIR = build
OBJ_SRC_DIR = $(OBJ_DIR)/src
OBJ_TEST_DIR = $(OBJ_DIR)/test
INCLUDE_DIR = include
OUTPUT_DIR = output
TEST_DIR = test
LOG_DIR = logs

# File for printf stdout
STDOUT_FILE = stdout.txt  # The file where stdout from the program will be saved

# Program name and target
PROGRAM = iZ  # The name of the final program binary
TARGET = $(OBJ_SRC_DIR)/$(PROGRAM)  # The target binary to be built in the build/src directory

# Source and object files
SOURCES = $(shell find $(SRC_DIR) -name "*.c")  # List all .c files in the source directory
OBJECTS = $(patsubst $(SRC_DIR)/%.c, $(OBJ_SRC_DIR)/%.o, $(SOURCES))  # Convert the list of .c files to a list of .o files in the build/src directory

# Test source and object files (excluding main.o)
TEST_SOURCES = $(wildcard $(TEST_DIR)/*.c)  # List all .c files in the test directory
TEST_OBJECTS = $(patsubst $(TEST_DIR)/%.c, $(OBJ_TEST_DIR)/%.o, $(TEST_SOURCES))  # Convert the list of .c files to .o files in the build/test directory
TEST_BUILD_OBJECTS = $(filter-out $(OBJ_SRC_DIR)/main.o, $(OBJECTS)) $(TEST_OBJECTS)  # Test build objects excluding the main.o

# Library objects for linking tools/examples (exclude the app entry point)
LIB_OBJECTS = $(filter-out $(OBJ_SRC_DIR)/main.o, $(OBJECTS))

# Dependency files
DEPS = $(OBJECTS:.o=.d) $(TEST_OBJECTS:.o=.d)  # List of dependency files (automatically generated by the compiler)

# Output file
OUTPUT = $(OUTPUT_DIR)/$(STDOUT_FILE)  # The final output file where stdout is stored

# Default target
all: directories $(TARGET) run

# ---------------------------------------------------------
# Examples
# ---------------------------------------------------------
EXAMPLES_DIR = examples
EXAMPLES_OBJ_DIR = $(OBJ_DIR)/examples
EXAMPLE_SOURCES = $(wildcard $(EXAMPLES_DIR)/*.c)
EXAMPLE_BINS = $(patsubst $(EXAMPLES_DIR)/%.c,$(EXAMPLES_OBJ_DIR)/%,$(EXAMPLE_SOURCES))

examples: directories $(EXAMPLE_BINS)

$(EXAMPLES_OBJ_DIR)/%: $(EXAMPLES_DIR)/%.c $(LIB_OBJECTS)
	@mkdir -p $(EXAMPLES_OBJ_DIR)
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ $< $(LIB_OBJECTS) $(LDFLAGS) $(LDLIBS)

# Run a single example:
#   make run-example EX=sieve_primes ARGS="SiZm 10000000 10"
EX ?=
ARGS ?=
run-example: examples
	@test -n "$(EX)" || (echo "Set EX=<example_name> (without path)" && exit 2)
	./$(EXAMPLES_OBJ_DIR)/$(EX) $(ARGS)

# ---------------------------------------------------------
# Documentation (Doxygen + LaTeX PDF)
# ---------------------------------------------------------
DOXYFILE ?= Doxyfile
DOCS_DIR = docs
DOCS_LATEX_DIR = $(DOCS_DIR)/api/latex
DOCS_PDF = $(DOCS_DIR)/userManual.pdf
DOCS_LOG_DIR = $(DOCS_DIR)/logs
DOCS_DOXY_LOG = $(DOCS_LOG_DIR)/doxygen.log
DOCS_LATEX_LOG = $(DOCS_LOG_DIR)/latex.log

userManual:
	@mkdir -p $(DOCS_LOG_DIR)
	@echo "Running Doxygen (log: $(DOCS_DOXY_LOG))..."
	@doxygen $(DOXYFILE) > $(DOCS_DOXY_LOG) 2>&1
	@echo "Building LaTeX manual (log: $(DOCS_LATEX_LOG))..."
	@$(MAKE) -C $(DOCS_LATEX_DIR) clean > $(DOCS_LATEX_LOG) 2>&1
	@$(MAKE) -C $(DOCS_LATEX_DIR) >> $(DOCS_LATEX_LOG) 2>&1
	@cp $(DOCS_LATEX_DIR)/refman.pdf $(DOCS_PDF)
	@echo "Generated $(DOCS_PDF)"

# Backward-compatible alias. Prefer `make userManual`.
docs: userManual

# Create necessary directories
directories:
	@mkdir -p $(OBJ_SRC_DIR) $(OBJ_TEST_DIR) $(OUTPUT_DIR) $(LOG_DIR) # Create build/, build/src/, build/test/, output/, and logs/ directories

# Build the program
$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(LDLIBS)

# Compile source files into object files and mirror the folder structure in build/src
$(OBJ_SRC_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)  # Create the necessary directory structure in build/src
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

# Compile test files into object files and mirror the folder structure in build/test
$(OBJ_TEST_DIR)/%.o: $(TEST_DIR)/%.c
	@mkdir -p $(dir $@)  # Create the necessary directory structure for test objects in build/test
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

# Include dependency files
-include $(DEPS)

# Run the program and save the output
run: $(TARGET)
	@mkdir -p $(OUTPUT_DIR)
	./$(TARGET) >> $(OUTPUT) 2>&1

# New test framework targets
NEW_TEST_DIR = test
# Include test_all.c and individual test files, but exclude any legacy tests.c
NEW_TEST_SOURCES = $(shell find $(NEW_TEST_DIR) -name "*.c" ! -name "tests.c")
NEW_TEST_OBJECTS = $(patsubst $(NEW_TEST_DIR)/%.c, $(OBJ_DIR)/$(NEW_TEST_DIR)/%.o, $(NEW_TEST_SOURCES))
# Exclude main.o from source objects since test_all.c provides main()
NEW_TEST_BUILD_OBJECTS = $(filter-out $(OBJ_SRC_DIR)/main.o, $(OBJECTS)) $(NEW_TEST_OBJECTS)

# ---------------------------------------------------------
# Test runner API
# ---------------------------------------------------------
# Usage examples:
#   make test-all
#   make test-unit verbose
#   make -- test-unit --verbose
#   make test-integration TEST_OUTPUT=output/integration.txt
#   make benchmark-p_sieve save-results
#   make benchmark-p_gen plot
#   make -- benchmark-p_sieve --save-results --plot

VERBOSE ?= 0
SAVE_RESULTS ?= 0
PLOT ?= 0
TEST_OUTPUT ?=
TEST_ARGS ?=
PYTHON ?= python3
PLOT_ENTRYPOINT = py_tools/plot_results.py

CLI_FLAG_TARGETS = verbose save-results plot --verbose --save-results --plot

ifneq (,$(filter verbose --verbose,$(MAKECMDGOALS)))
VERBOSE := 1
endif

ifneq (,$(filter save-results --save-results,$(MAKECMDGOALS)))
SAVE_RESULTS := 1
endif

ifneq (,$(filter plot --plot,$(MAKECMDGOALS)))
PLOT := 1
SAVE_RESULTS := 1
endif

TEST_RUNNER = $(OBJ_DIR)/$(NEW_TEST_DIR)/test_runner
TEST_ARGS_COMMON = $(if $(filter 1,$(VERBOSE)),--verbose,) \
			   $(if $(filter 1,$(SAVE_RESULTS)),--save-results,) \
			   $(TEST_ARGS)

define RUN_TEST
	@echo "Running: $(TEST_RUNNER) $(1) $(TEST_ARGS_COMMON)"
	$(if $(strip $(TEST_OUTPUT)),./$(TEST_RUNNER) $(1) $(TEST_ARGS_COMMON) > $(TEST_OUTPUT) 2>&1,./$(TEST_RUNNER) $(1) $(TEST_ARGS_COMMON))
endef

define RUN_BENCHMARK
	@echo "Running: $(TEST_RUNNER) $(1) $(TEST_ARGS_COMMON)"
	@tmp_file=$$(mktemp); \
	./$(TEST_RUNNER) $(1) $(TEST_ARGS_COMMON) > "$$tmp_file" 2>&1; \
	status=$$?; \
	cat "$$tmp_file"; \
	if [ -n "$(strip $(TEST_OUTPUT))" ]; then \
		cp "$$tmp_file" "$(TEST_OUTPUT)"; \
	fi; \
	if [ $$status -ne 0 ]; then \
		rm -f "$$tmp_file"; \
		exit $$status; \
	fi; \
	if [ "$(PLOT)" = "1" ]; then \
		result_paths=$$(grep '^RESULTS_FILE:' "$$tmp_file" | sed 's/^RESULTS_FILE:[[:space:]]*//'); \
		if [ -z "$$result_paths" ]; then \
			echo "No results files detected in benchmark output; skipping plot generation."; \
		else \
			for result_path in $$result_paths; do \
				echo "Plotting $$result_path"; \
				$(PYTHON) $(PLOT_ENTRYPOINT) "$$result_path" --save --no-show || exit $$?; \
			done; \
		fi; \
	fi; \
	rm -f "$$tmp_file"
endef

# Compile new test files
$(OBJ_DIR)/$(NEW_TEST_DIR)/%.o: $(NEW_TEST_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

# CLI-flag pseudo-targets (usable as: make test-all verbose)
$(CLI_FLAG_TARGETS):
	@:

# Build test runner once and reuse for all test/benchmark targets
$(TEST_RUNNER): directories $(NEW_TEST_BUILD_OBJECTS)
	@mkdir -p $(OBJ_DIR)/$(NEW_TEST_DIR)
	@echo "Building test runner..."
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(TEST_RUNNER) $(NEW_TEST_BUILD_OBJECTS) $(LDFLAGS) $(LDLIBS)

# Build and run new test framework
test-all: $(TEST_RUNNER)
	@echo "Running tests..."
	$(call RUN_TEST,--all)

test-unit: $(TEST_RUNNER)
	@echo "Running unit tests..."
	$(call RUN_TEST,--unit)

test-integration: $(TEST_RUNNER)
	@echo "Running integration tests..."
	$(call RUN_TEST,--integration)

# Dedicated benchmark drivers
benchmark-p_sieve: $(TEST_RUNNER)
	@echo "Running prime sieve model benchmarks..."
	@echo "Warning: Benchmarks may take time and could have memory issues"
	$(call RUN_BENCHMARK,--benchmark-p-sieve)

benchmark-p_gen: $(TEST_RUNNER)
	@echo "Running random prime generation benchmarks..."
	@echo "Warning: Benchmarks may take time and could have memory issues"
	$(call RUN_BENCHMARK,--benchmark-p-gen)

# Hyphen aliases
benchmark-p-sieve: benchmark-p_sieve
benchmark-p-gen: benchmark-p_gen

# Legacy test support (backward compatibility)
test: directories $(TEST_OBJECTS) $(TEST_BUILD_OBJECTS)
	@mkdir -p $(OBJ_TEST_DIR)
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $(OBJ_TEST_DIR)/test_runner $(TEST_BUILD_OBJECTS) $(LDFLAGS) $(LDLIBS)
	./$(OBJ_TEST_DIR)/test_runner

# Clean generated files
clean:
	rm -rf $(OBJ_DIR) $(OUTPUT_DIR) $(LOG_DIR)

# Build with debug flags
debug: LOGGING = 1
debug: CFLAGS_OPT = -O0
debug: CFLAGS_DBG = -g
debug: $(TARGET)

# Build optimized release version without logging
release: LOGGING = 0
release: CFLAGS_OPT = -O3 -flto
release: CFLAGS_DBG =
release: $(TARGET)

# Help message
help:
	@echo "=========================================="
	@echo "  iZprime Project Build System"
	@echo "=========================================="
	@echo "Main targets:"
	@echo "  all             - Build the main program and run it"
	@echo "  run             - Run the main program (builds if needed)"
	@echo "  clean           - Remove all generated files"
	@echo ""
	@echo "Test targets:"
	@echo "  test-all        - Run all tests (recommended)"
	@echo "  test-unit       - Run only unit tests"
	@echo "  test-integration- Run only integration tests"
	@echo "  benchmark-p_sieve - Run prime sieve model benchmarks"
	@echo "  benchmark-p-sieve - Alias for benchmark-p_sieve"
	@echo "  benchmark-p_gen   - Run random prime generation benchmarks"
	@echo "  benchmark-p-gen   - Alias for benchmark-p_gen"
	@echo "  test            - Run legacy tests (deprecated)"
	@echo ""
	@echo "Test/benchmark options:"
	@echo "  verbose / --verbose         - Enable verbose test output"
	@echo "  save-results / --save-results - Save benchmark result files"
	@echo "  plot / --plot               - Save results and generate plot(s)"
	@echo "  Note: use GNU make '--' before dashed goals:"
	@echo "        make -- test-all --verbose"
	@echo "  TEST_OUTPUT=<path> - Redirect test stdout/stderr to file"
	@echo "  TEST_ARGS=...   - Extra args passed to test_runner"
	@echo ""
	@echo "Build variants:"
	@echo "  debug           - Build with debug flags and logging"
	@echo "  release         - Build optimized release version"
	@echo ""
	@echo "Utility:"
	@echo "  help            - Show this help message"
	@echo "  examples        - Build example programs (build/examples/*)"
	@echo "  run-example     - Run an example (EX=..., ARGS=...)"
	@echo "  userManual      - Generate docs/userManual.pdf from Doxygen + LaTeX"
	@echo ""
	@echo "Examples:"
	@echo "  make              # Build and run main program"
	@echo "  make test-all     # Run all tests"
	@echo "  make test-unit verbose"
	@echo "  make -- test-unit --verbose"
	@echo "  make benchmark-p_sieve save-results"
	@echo "  make benchmark-p_gen plot"
	@echo "  make test-integration TEST_OUTPUT=output/integration.txt"
	@echo "  make examples"
	@echo "  make run-example EX=sieve_primes ARGS=\"SiZm 10000000 10\""
	@echo "  make clean        # Clean build artifacts"
	@echo "=========================================="

# Phony targets
.PHONY: all run test test-all test-unit test-integration benchmark-p_sieve benchmark-p_gen benchmark-p-sieve benchmark-p-gen clean debug release help directories examples run-example userManual docs $(CLI_FLAG_TARGETS)

# Delete incomplete files if a command fails
.DELETE_ON_ERROR:
