# Help message
help:
	@echo "=========================================="
	@echo "  iZprime Project Build System"
	@echo "=========================================="
	@echo "Main targets:"
	@echo "  all             - Build the main program and run it"
	@echo "  lib             - Build library artifacts (static + shared when enabled)"
	@echo "  cli             - Build CLI binary: build/bin/$(PROGRAM)"
	@echo "  run             - Run the main program (builds if needed)"
	@echo "  clean           - Remove all generated files"
	@echo ""
	@echo "Test targets:"
	@echo "  test-all        - Run all tests (recommended)"
	@echo "  test-unit       - Run only unit tests"
	@echo "  test-integration- Run only integration tests"
	@echo "  benchmark-p_sieve - Run prime sieve model benchmarks"
	@echo "  benchmark-p-sieve - Alias for benchmark-p_sieve"
	@echo "  benchmark-p_gen   - Run random prime generation benchmarks"
	@echo "  benchmark-p-gen   - Alias for benchmark-p_gen"
	@echo "  benchmark-SiZ_count - Run SiZ_count benchmark (10^9 windows from 10^10..10^100)"
	@echo "  benchmark-siz-count - Alias for benchmark-SiZ_count"
	@echo "  test            - Run legacy tests (deprecated)"
	@echo ""
	@echo "Test/benchmark options:"
	@echo "  verbose / --verbose         - Enable verbose test output"
	@echo "  save-results / --save-results - Save benchmark result files"
	@echo "  plot / --plot               - Save results and generate plot(s)"
	@echo "  Note: use GNU make '--' before dashed goals:"
	@echo "        make -- test-all --verbose"
	@echo "  TEST_OUTPUT=<path> - Redirect test stdout/stderr to file"
	@echo "  TEST_ARGS=...   - Extra args passed to test_runner"
	@echo ""
	@echo "Build variants:"
	@echo "  debug           - Build with debug flags and logging"
	@echo "  release         - Build optimized release version"
	@echo "  pgo-generate    - Build with profile instrumentation (run workload after)"
	@echo "  pgo-use         - Build using collected profile data from $(PGO_DIR)"
	@echo ""
	@echo "Performance toggles (override on make command):"
	@echo "  ARCH_NATIVE=1/0     - Enable/disable -march=native"
	@echo "  TUNE_NATIVE=1/0     - Enable/disable -mtune=native"
	@echo "  ENABLE_NDEBUG=1/0   - Enable/disable -DNDEBUG in release/PGO targets"
	@echo "  ENABLE_STRIP_DEAD=1/0 - Enable/disable dead-code stripping flags"
	@echo "  USE_CCACHE=1/0      - Prefix compiler with ccache"
	@echo "  VERSION=x.y.z       - Library/CLI version metadata (default: 1.0.0)"
	@echo "  SOVERSION=n         - Shared-library ABI major (default: VERSION major)"
	@echo "  BUILD_SHARED=1/0    - Build shared library artifacts"
	@echo ""
	@echo "Utility:"
	@echo "  help            - Show this help message"
	@echo "  examples        - Build example programs (build/examples/*)"
	@echo "  run-example     - Run an example (EX=..., ARGS=...)"
	@echo "  userManual      - Generate docs/userManual.pdf from Doxygen + LaTeX"
	@echo "  install         - Install headers, static lib, and CLI"
	@echo "  install-lib     - Install headers and static lib only"
	@echo "  uninstall       - Remove installed files"
	@echo "  doctor          - Verify required build dependencies"
	@echo "  dist            - Create release source tarball + SHA256"
	@echo ""
	@echo "Examples:"
	@echo "  make              # Build and run main program"
	@echo "  make lib          # Build static + shared libraries"
	@echo "  make test-all     # Run all tests"
	@echo "  make test-unit verbose"
	@echo "  make -- test-unit --verbose"
	@echo "  make benchmark-p_sieve save-results"
	@echo "  make benchmark-p_gen plot"
	@echo "  make benchmark-SiZ_count"
	@echo "  make test-integration TEST_OUTPUT=output/integration.txt"
	@echo "  make examples"
	@echo "  make run-example EX=sieve_primes ARGS=\"SiZm 10000000 10\""
	@echo "  make install PREFIX=\$$HOME/.local"
	@echo "  make doctor"
	@echo "  make dist VERSION=1.0.0"
	@echo "  cp config.mk.example config.mk  # Local, persistent build options"
	@echo "  make clean        # Clean build artifacts"
	@echo "=========================================="

PHONY_TARGETS += help
