iZ-Library: Bitmap Module
Bitmap Module
Packed bit-array primitives for sieve and toolkit modules.
Files
file bitmap.c
Implementation of the bitmap module for efficient bit array operations.
Data Structures
struct BITMAP
Packed bit-array with optional SHA-256 checksum.
Functions
int TEST_BITMAP (int verbose)
Run bitmap module tests.
Lifecycle
BITMAP * bitmap_init (size_t size, int set_bits)
Allocate a bitmap with size bits.
void bitmap_free (BITMAP **bitmap)
Free a bitmap and set the caller pointer to NULL.
BITMAP * bitmap_clone (BITMAP *src)
Deep-copy a bitmap, including data and checksum.
Single-bit Operations
int bitmap_get_bit (BITMAP *bitmap, size_t idx)
Read bit value at idx.
void bitmap_set_bit (BITMAP *bitmap, size_t idx)
Set bit at idx to 1.
void bitmap_flip_bit (BITMAP *bitmap, size_t idx)
Toggle bit at idx.
void bitmap_clear_bit (BITMAP *bitmap, size_t idx)
Clear bit at idx (set to 0).
Bulk Operations
void bitmap_set_all (BITMAP *bitmap)
Set all bits to 1.
void bitmap_clear_all (BITMAP *bitmap)
Clear all bits to 0.
void bitmap_clear_steps (BITMAP *bitmap, uint64_t step, uint64_t start_idx, uint64_t limit)
Clear every step-th bit from start_idx up to limit.
void bitmap_clear_steps_simd (BITMAP *bitmap, uint64_t step, uint64_t start_idx, uint64_t limit)
SIMD-accelerated variant of bitmap_clear_steps().
Integrity and I/O
void bitmap_compute_hash (BITMAP *bitmap)
Compute SHA-256 over bitmap data and store it in BITMAP::sha256.
int bitmap_validate_hash (BITMAP *bitmap)
Verify BITMAP::sha256 against current bitmap data.
int bitmap_fwrite (BITMAP *bitmap, FILE *file)
Write bitmap payload and checksum to a binary stream.
BITMAP * bitmap_fread (FILE *file)
Read bitmap payload and checksum from a binary stream.
Detailed Description
Packed bit-array primitives for sieve and toolkit modules.
Function Documentation
bitmap_clear_all()
void bitmap_clear_all (BITMAP * bitmap)
Clear all bits to 0.
Parameters
bitmap Bitmap to modify.
Clear all bits to 0.
Parameters
bitmap A pointer to the BITMAP structure.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 180 of file bitmap.c.
References BITMAP::data, and BITMAP::size.
bitmap_clear_bit()
void bitmap_clear_bit (BITMAP * bitmap, size_t idx)
Clear bit at idx (set to 0).
Parameters
bitmap Bitmap to modify.
idx Zero-based bit index.
Clear bit at idx (set to 0).
Parameters
bitmap The BITMAP to modify.
idx The index of the bit to clear.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 159 of file bitmap.c.
References BITMAP::data.
Referenced by iZm_construct_vx_base(), SoEu(), vx_prob_sieve(), and vx_stream().
bitmap_clear_steps()
void bitmap_clear_steps (BITMAP * bitmap, uint64_t step, uint64_t start_idx, uint64_t limit)
Clear every step-th bit from start_idx up to limit.
This is the core primitive for marking composite progressions in sieve code.
Parameters
bitmap Bitmap to modify.
step Index increment between cleared bits.
start_idx First index to clear.
limit Inclusive upper index bound.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 210 of file bitmap.c.
References BITMAP::data, MIN, and BITMAP::size.
Referenced by vx_search_prime().
bitmap_clear_steps_simd()
void bitmap_clear_steps_simd (BITMAP * bitmap, uint64_t step, uint64_t start_idx, uint64_t limit)
SIMD-accelerated variant of bitmap_clear_steps().
Parameters
bitmap Bitmap to modify.
step Index increment between cleared bits.
start_idx First index to clear.
limit Inclusive upper index bound.
SIMD-accelerated variant of bitmap_clear_steps().
This function uses SIMD instructions (AVX2, SSE2, or NEON) to clear bits at regular intervals in the bitmap. It processes multiple bits in parallel for improved performance on large bitmaps.
Parameters
bitmap Pointer to the bitmap to modify
step Interval between bits to clear (must be > 0)
start_idx Starting bit index (inclusive)
limit Upper bound for clearing (inclusive)
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 233 of file bitmap.c.
References BITMAP::data, MIN, and BITMAP::size.
Referenced by iZm_construct_vx_base(), process_iZ_bitmaps(), process_N_bitmap(), SiZm(), SiZm_vy(), SoA(), SoS(), SSoE(), and vx_det_sieve().
bitmap_clone()
BITMAP * bitmap_clone (BITMAP * src)
Deep-copy a bitmap, including data and checksum.
Parameters
src Source bitmap.
Returns
Cloned bitmap, or NULL on failure.
Deep-copy a bitmap, including data and checksum.
Allocates a new bitmap with the same size as the source and copies all data including the bit array and SHA-256 hash. The returned bitmap is completely independent of the source and must be freed separately.
Parameters
src Pointer to the source bitmap to clone
Returns
Pointer to newly allocated cloned BITMAP, or NULL on failure
Return values
NULL if src is NULL, src->size is 0, or memory allocation fails
Note
The clone includes a copy of the SHA-256 hash from the source
Caller must free the returned bitmap using bitmap_free()
Changes to the clone do not affect the source and vice versa
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 382 of file bitmap.c.
References bitmap_init(), BITMAP::byte_size, BITMAP::data, BITMAP::sha256, and BITMAP::size.
Referenced by iZm_clone(), SiZm(), and vx_init().
bitmap_compute_hash()
void bitmap_compute_hash (BITMAP * bitmap)
Compute SHA-256 over bitmap data and store it in BITMAP::sha256.
Parameters
bitmap Bitmap to hash.
Compute SHA-256 over bitmap data and store it in BITMAP::sha256.
Parameters
bitmap The BITMAP for which the SHA-256 hash is generated.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 398 of file bitmap.c.
References BITMAP::byte_size, BITMAP::data, and BITMAP::sha256.
Referenced by bitmap_fwrite().
bitmap_flip_bit()
void bitmap_flip_bit (BITMAP * bitmap, size_t idx)
Toggle bit at idx.
Parameters
bitmap Bitmap to modify.
idx Zero-based bit index.
Toggle bit at idx.
Parameters
bitmap The BITMAP to modify.
idx The index of the bit to flip.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 148 of file bitmap.c.
References BITMAP::data.
Referenced by SoA().
bitmap_fread()
BITMAP * bitmap_fread (FILE * file)
Read bitmap payload and checksum from a binary stream.
Parameters
file Readable stream.
Returns
Newly allocated bitmap, or NULL on parse/verification failure.
Read bitmap payload and checksum from a binary stream.
Parameters
file The file pointer to read from.
Returns
BITMAP* A pointer to the newly created BITMAP, or NULL on failure.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 492 of file bitmap.c.
References bitmap_free(), bitmap_init(), bitmap_validate_hash(), BITMAP::byte_size, BITMAP::data, log_error(), and BITMAP::sha256.
bitmap_free()
void bitmap_free (BITMAP ** bitmap)
Free a bitmap and set the caller pointer to NULL.
Parameters
bitmap Address of a BITMAP pointer.
Free a bitmap and set the caller pointer to NULL.
This function safely deallocates the bitmap's data array and the structure itself, then sets the pointer to NULL to prevent use-after-free bugs and double-free errors. Safe to call with NULL pointers.
Parameters
bitmap Double pointer to the BITMAP to free
Postcondition
*bitmap is set to NULL after successful deallocation
Safe to call multiple times on the same pointer
Note
No operation performed if bitmap == NULL or *bitmap == NULL
This is the only correct way to free a BITMAP; never use free() directly
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 103 of file bitmap.c.
Referenced by bitmap_fread(), get_root_primes(), iZm_free(), SiZ(), SiZm(), SiZm_vy(), SoA(), SoE(), SoEu(), SoS(), SSoE(), vx_free(), and vx_search_prime().
bitmap_fwrite()
int bitmap_fwrite (BITMAP * bitmap, FILE * file)
Write bitmap payload and checksum to a binary stream.
Parameters
bitmap Bitmap to serialize.
file Writable stream.
Returns
1 on success, otherwise 0.
Write bitmap payload and checksum to a binary stream.
Parameters
bitmap The BITMAP to write.
file The file pointer to write to.
Returns
int 1 on success, 0 on failure.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 440 of file bitmap.c.
References bitmap_compute_hash(), BITMAP::byte_size, BITMAP::data, log_error(), BITMAP::sha256, and BITMAP::size.
bitmap_get_bit()
int bitmap_get_bit (BITMAP * bitmap, size_t idx)
Read bit value at idx.
Parameters
bitmap Bitmap to inspect.
idx Zero-based bit index.
Returns
1 if set, otherwise 0.
Read bit value at idx.
Parameters
bitmap The BITMAP to read from.
idx The index of the bit to read.
Returns
int 1 if the bit is set, 0 if unset, -1 on error.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 137 of file bitmap.c.
References BITMAP::data.
Referenced by iZ_next_prime(), process_iZ_bitmaps(), process_N_bitmap(), SiZm(), SiZm_vy(), SoA(), SoEu(), SoS(), SSoE(), vx_collect_p_gaps(), vx_det_sieve(), vx_prob_sieve(), vx_search_prime(), and vx_stream().
bitmap_init()
BITMAP * bitmap_init (size_t size, int set_bits)
Allocate a bitmap with size bits.
Parameters
size Number of bits to allocate (must be > 0).
set_bits Non-zero initializes all bits to 1, otherwise to 0.
Returns
Newly allocated bitmap, or NULL on allocation failure.
Allocate a bitmap with size bits.
Allocates memory for both the BITMAP structure and its underlying data array. The data array is allocated using calloc(), ensuring all bits start at 0. The SHA-256 hash field is initialized to all zeros.
Parameters
size The number of bits in the bitmap (must be > 0)
set_bits If non-zero, initializes all bits to 1; otherwise, all bits are 0.
Returns
Pointer to newly allocated BITMAP on success, NULL on failure
Return values
NULL if size is 0
NULL if memory allocation fails
Note
Memory allocated: sizeof(BITMAP) + ⌈size/8⌉ bytes
On failure, any partially allocated memory is freed before returning
Warning
Caller must free returned bitmap using bitmap_free(), not free()
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 57 of file bitmap.c.
References BITMAP::byte_size, BITMAP::data, log_error(), BITMAP::sha256, and BITMAP::size.
Referenced by bitmap_clone(), bitmap_fread(), get_root_primes(), iZm_init(), SiZ(), SiZm(), SiZm_vy(), SoA(), SoE(), SoEu(), SoS(), SSoE(), and vx_search_prime().
bitmap_set_all()
void bitmap_set_all (BITMAP * bitmap)
Set all bits to 1.
Parameters
bitmap Bitmap to modify.
Set all bits to 1.
Parameters
bitmap The BITMAP to modify.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 170 of file bitmap.c.
References BITMAP::data, and BITMAP::size.
Referenced by iZm_construct_vx_base(), SiZm_vy(), and SSoE().
bitmap_set_bit()
void bitmap_set_bit (BITMAP * bitmap, size_t idx)
Set bit at idx to 1.
Parameters
bitmap Bitmap to modify.
idx Zero-based bit index.
Set bit at idx to 1.
Parameters
bitmap The BITMAP to modify.
idx The index of the bit to set.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 125 of file bitmap.c.
References BITMAP::data.
bitmap_validate_hash()
int bitmap_validate_hash (BITMAP * bitmap)
Verify BITMAP::sha256 against current bitmap data.
Parameters
bitmap Bitmap to verify.
Returns
1 if checksum matches, otherwise 0.
Verify BITMAP::sha256 against current bitmap data.
Parameters
bitmap The BITMAP whose hash is validated.
Returns
int 1 if the hash matches, 0 otherwise.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 412 of file bitmap.c.
References BITMAP::byte_size, BITMAP::data, log_error(), and BITMAP::sha256.
Referenced by bitmap_fread().
TEST_BITMAP()
int TEST_BITMAP (int verbose)
Run bitmap module tests.
Parameters
verbose Non-zero enables detailed logging.
Returns
1 when all tests pass, otherwise 0.