iZ-Library: Toolkit (iZ/iZm)
Toolkit (iZ/iZm)
Internal building blocks for SiZ and SiZm implementations.
Files
file iZ_toolkit.c
Implementation of iZ index space helpers and iZm/VX segment machinery.
Data Structures
struct IZM
Precomputed iZm assets for repeated VX-segment sieving.
struct VX_SEG
Runtime state for one VX segment at a specific y.
struct IZM_RANGE_INFO
Precomputed iZm coordinates for an inclusive numeric interval.
Macros
#define MR_ROUNDS 25
Functions
void iZm_construct_vx_base (uint64_t vx, BITMAP *base_x5, BITMAP *base_x7)
Build pre-sieved base bitmaps for a VX segment.
IZM_RANGE_INFO range_info_init (INPUT_SIEVE_RANGE *input_range, int vx)
Map a decimal range input into iZm coordinates and segment bounds.
void range_info_free (IZM_RANGE_INFO *info)
Clear all GMP fields owned by info.
iZ Mapping Helpers
uint64_t iZ (uint64_t x, int i)
Map iZ coordinates to an integer: 6*x + i.
void iZ_mpz (mpz_t z, mpz_t x, int i)
GMP variant of iZ().
void process_iZ_bitmaps (UI64_ARRAY *primes, BITMAP *x5, BITMAP *x7, uint64_t x_limit)
Traverse iZ bitmaps, emit surviving primes, and mark composites.
void get_root_primes (UI64_ARRAY *primes, uint64_t limit)
Generate primes up to limit for deterministic sieving.
int check_primality (mpz_t n, int rounds)
Check the primality of a number using GMP's probabilistic test.
IZM Lifecycle
IZM * iZm_init (size_t vx)
Allocate and initialize an IZM object for a given VX.
IZM * iZm_clone (IZM *src)
Deep-copy an IZM object for per-worker ownership.
void iZm_free (IZM **iZm)
Release an IZM object and set the caller pointer to NULL.
VX Selection Helpers
uint64_t compute_vx_k (int k)
Calculate VX_{ k }.
uint64_t compute_l2_vx (uint64_t n)
Choose VX using an L2-cache-aware heuristic.
void compute_max_vx (mpz_t vx, int bit_size)
Compute largest VX below 2^bit_size.
Modular Hit Solvers
uint64_t iZm_solve_for_x0 (int m_id, uint64_t p, uint64_t vx, uint64_t y)
Solve first x-hit of prime p for line m_id in segment y.
uint64_t iZm_solve_for_x0_mpz (int m_id, uint64_t p, uint64_t vx, mpz_t y)
GMP variant of iZm_solve_for_x0() for very large y.
int64_t iZm_solve_for_y0 (int m_id, uint64_t p, uint64_t vx, uint64_t x)
Solve first y-hit for fixed x in vertical (vy) scanning.
VX Segment Lifecycle and Execution
VX_SEG * vx_init (IZM *iZm, int start_x, int end_x, char *y_str, int mr_rounds)
Initialize and deterministically sieve one VX segment.
void vx_free (VX_SEG **vx_obj)
Free a VX segment and all owned resources.
void vx_collect_p_gaps (VX_SEG *vx_obj)
Extract prime-gap encoding from a fully sieved segment.
void vx_full_sieve (VX_SEG *vx_obj, int collect_p_gaps)
Complete segment processing (probabilistic stage and optional gaps).
void vx_stream (VX_SEG *vx_obj, FILE *output)
Stream segment primes to an output stream.
Random Prime Search Routines
int vx_search_prime (mpz_t p, int m_id, int vx, int bit_size)
Horizontal iZm/VX random-prime search.
int vy_search_prime (mpz_t p, int m_id, mpz_t vx)
Vertical iZm/VY random-prime search.
Toolkit Tests
int TEST_IZM (int verbose)
Run IZM construction and solver tests.
int TEST_VX_SEG (int verbose)
Run VX segment tests.
Standard VX Sizes (primorial products excluding 2,3)
#define VX2 (5 * 7ULL)
#define VX3 (VX2 * 11ULL)
#define VX4 (VX3 * 13ULL)
#define VX5 (VX4 * 17ULL)
#define VX6 (VX5 * 19ULL)
#define VX7 (VX6 * 23ULL)
#define VX8 (VX7 * 29ULL)
Detailed Description
Internal building blocks for SiZ and SiZm implementations.
Macro Definition Documentation
MR_ROUNDS
#define MR_ROUNDS 25
Default Miller-Rabin rounds used by toolkit search/sieve helpers.
Definition at line 79 of file iZ_toolkit.h.
Referenced by iZ_next_prime(), vx_init(), vx_search_prime(), and vy_search_prime().
VX2
#define VX2 (5 * 7ULL)
35
Definition at line 69 of file iZ_toolkit.h.
VX3
#define VX3 (VX2 * 11ULL)
385
Definition at line 70 of file iZ_toolkit.h.
VX4
#define VX4 (VX3 * 13ULL)
5005
Definition at line 71 of file iZ_toolkit.h.
VX5
#define VX5 (VX4 * 17ULL)
85085
Definition at line 72 of file iZ_toolkit.h.
Referenced by iZ_next_prime(), and vx_random_prime().
VX6
#define VX6 (VX5 * 19ULL)
1616615
Definition at line 73 of file iZ_toolkit.h.
Referenced by iZ_next_prime(), SiZ_stream(), and vx_random_prime().
VX7
#define VX7 (VX6 * 23ULL)
37260615
Definition at line 74 of file iZ_toolkit.h.
VX8
#define VX8 (VX7 * 29ULL)
1080558835
Definition at line 75 of file iZ_toolkit.h.
Function Documentation
check_primality()
int check_primality (mpz_t n, int rounds)
Check the primality of a number using GMP's probabilistic test.
Parameters
n Number to check.
rounds Number of Miller-Rabin rounds.
Returns
Non-zero if probably prime, 0 if composite.
Parameters
n Number to check.
rounds Number of Miller-Rabin rounds.
Returns
Non-zero if probably prime, 0 if composite.
This function serves as a single source of truth for primality testing, wrapping GMP's mpz_probab_prime_p function, allowing for changes to the underlying primality testing method in the future without affecting the API.
Definition at line 153 of file iZ_toolkit.c.
Referenced by vx_prob_sieve(), vx_search_prime(), vx_stream(), and vy_search_prime().
compute_l2_vx()
uint64_t compute_l2_vx (uint64_t n)
Choose VX using an L2-cache-aware heuristic.
Choose a cache-aware VX size based on detected L2 capacity.
Parameters
n Target numeric limit.
Returns
Selected VX size.
Parameters
n Target numeric sieve bound.
Returns
L2 compatible VX size.
Definition at line 306 of file iZ_toolkit.c.
References get_cpu_L2_cache_size_bits(), MIN, and s_primes.
Referenced by SiZ_count(), and SiZm().
compute_max_vx()
void compute_max_vx (mpz_t vx, int bit_size)
Compute largest VX below 2^bit_size.
Compute the maximum vx such that vx < 2^bit_size.
Parameters
vx Output mpz_t containing VX.
bit_size Bit-size ceiling.
Parameters:
Parameters
vx mpz_t variable to store the computed maximum vx value.
bit_size Integer representing the bit size limit for vx.
Definition at line 331 of file iZ_toolkit.c.
References UI64_ARRAY::array, and SiZ().
Referenced by vy_random_prime().
compute_vx_k()
uint64_t compute_vx_k (int k)
Calculate VX_{ k }.
Calculate a VX_{k} as the product of the first k primes > 3.
Parameters
k Number of multiplicative prime factors (>3).
Returns
Selected VX size.
Parameters
k number of consecutive primes (> 3) to include in the product.
Returns
Computed VX_k value.
Definition at line 286 of file iZ_toolkit.c.
References s_primes.
get_root_primes()
void get_root_primes (UI64_ARRAY * primes, uint64_t limit)
Generate primes up to limit for deterministic sieving.
Generate root primes up to limit using iZ bitmap traversal.
Parameters
primes Output array, appended in ascending order.
limit Numeric upper bound.
primes Destination array.
limit Numeric upper bound.
Definition at line 112 of file iZ_toolkit.c.
References bitmap_free(), bitmap_init(), process_iZ_bitmaps(), ui64_free(), and ui64_push().
Referenced by SiZm_vy().
iZ()
uint64_t iZ (uint64_t x, int i) inline
Map iZ coordinates to an integer: 6*x + i.
Parameters
x iZ x-coordinate.
i Matrix identifier, typically -1 or +1.
Returns
Mapped integer value.
Map iZ coordinates to an integer: 6*x + i.
Parameters:
Parameters
x (uint64_t) The value of x in 6x + i.
i (int) The value of i in 6x + i.
Returns
The computed value 6x + i as a 64-bit unsigned integer.
Definition at line 24 of file iZ_toolkit.c.
Referenced by process_iZ_bitmaps(), SiZm(), and SiZm_vy().
iZ_mpz()
void iZ_mpz (mpz_t z, mpz_t x, int i)
GMP variant of iZ().
Parameters
z Output value.
x Input x-coordinate.
i Matrix identifier, typically -1 or +1.
GMP variant of iZ().
Parameters:
Parameters
z (mpz_t) The result of the calculation 6x + i.
x (mpz_t) The input value of x in 6x + i.
i (int) The value of i in 6x + i.
Definition at line 37 of file iZ_toolkit.c.
Referenced by iZ_next_prime(), SiZ_count(), vx_prob_sieve(), vx_search_prime(), vx_set_base_values(), vx_stream(), and vy_search_prime().
iZm_clone()
IZM * iZm_clone (IZM * src)
Deep-copy an IZM object for per-worker ownership.
Deep-copy an IZM object for independent worker usage.
Parameters
src Source IZM instance.
Returns
Newly allocated clone, or NULL on failure.
Parameters
src Source IZM object.
Returns
Cloned IZM object, or NULL on failure.
Definition at line 232 of file iZ_toolkit.c.
References UI64_ARRAY::array, IZM::base_x5, IZM::base_x7, bitmap_clone(), UI64_ARRAY::capacity, UI64_ARRAY::count, iZm_free(), IZM::k_vx, log_error(), IZM::root_primes, ui64_init(), and IZM::vx.
Referenced by SiZ_count().
iZm_construct_vx_base()
void iZm_construct_vx_base (uint64_t vx, BITMAP * base_x5, BITMAP * base_x7)
Build pre-sieved base bitmaps for a VX segment.
Constructs a pre-sieved iZm base segment of size vx.
Parameters
vx Segment width.
base_x5 Output bitmap for 6x-1 candidates.
base_x7 Output bitmap for 6x+1 candidates.
Description: This function constructs a pre-sieved iZm base segment of size vx. It marks all composites of small primes that divide vx in the bitmaps base_x5 (iZ-) and base_x7 (iZ+). This pre-sieved base can then be used as a template for sieving all vx segments.
Parameters:
Parameters
iZm Pointer to the IZM structure containing the base segment bitmaps.
Definition at line 363 of file iZ_toolkit.c.
References bitmap_clear_bit(), bitmap_clear_steps_simd(), bitmap_set_all(), s_primes, and s_primes_count.
Referenced by iZm_init(), and SiZm().
iZm_free()
void iZm_free (IZM ** iZm)
Release an IZM object and set the caller pointer to NULL.
Free the memory allocated for an IZM structure.
Parameters
iZm Address of an IZM pointer.
Parameters:
Parameters
iZm A pointer to the IZM structure to be freed.
Definition at line 266 of file iZ_toolkit.c.
References bitmap_free(), and ui64_free().
Referenced by iZ_next_prime(), iZm_clone(), iZm_init(), SiZ_count(), and SiZ_stream().
iZm_init()
IZM * iZm_init (size_t vx)
Allocate and initialize an IZM object for a given VX.
Initialize an iZm structure for a given vx size.
Parameters
vx Segment width; must be odd, not divisible by 3, and >= 35.
Returns
Initialized IZM object, or NULL on failure.
This function initializes an iZm structure for a specified vx size. It allocates memory for the structure, generates root primes for deterministic sieving, initializes base bitmaps, and constructs pre-sieved base segments for iZm5 and iZm7.
Parameters:
Parameters
vx The size of the segment for the iZm structure.
Returns
A pointer to the initialized IZM structure.
Definition at line 184 of file iZ_toolkit.c.
References IZM::base_x5, IZM::base_x7, bitmap_init(), compute_k_vx(), iZm_construct_vx_base(), iZm_free(), IZM::k_vx, log_error(), IZM::root_primes, SiZ(), ui64_free(), and IZM::vx.
Referenced by iZ_next_prime(), SiZ_count(), and SiZ_stream().
iZm_solve_for_x0()
uint64_t iZm_solve_for_x0 (int m_id, uint64_t p, uint64_t vx, uint64_t y)
Solve first x-hit of prime p for line m_id in segment y.
Compute the first composite hit of p in the yth vx segment in iZm index space.
Parameters
m_id Line id (-1 for x5, +1 for x7).
p Prime used for marking.
vx Segment width.
y Segment index.
Returns
First x index to clear for this prime/line.
Description: This function solves for the smallest x that satisfies: (x + vx * y) x_p (mod p), where x_p is normalized based on the m_id and p to either x_p or p - x_p, then computes x and returns it.
Parameters:
Parameters
m_id int matrix identifier (-1 for iZm5, 1 for iZm7).
p Unsigned 64-bit integer parameter.
vx size_t parameter representing the vx value.
y Unsigned 64-bit integer parameter.
Returns
The computed x value as a 64-bit unsigned integer.
Definition at line 415 of file iZ_toolkit.c.
Referenced by SiZm(), and vx_det_sieve().
iZm_solve_for_x0_mpz()
uint64_t iZm_solve_for_x0_mpz (int m_id, uint64_t p, uint64_t vx, mpz_t y)
GMP variant of iZm_solve_for_x0() for very large y.
Solve for x given m_id, p, vx, and y using GMP. Same as above but using GMP. Suitable for arbitrary y values.
Parameters
m_id Line id (-1 for x5, +1 for x7).
p Prime used for marking.
vx Segment width.
y Segment index as mpz.
Returns
First x index to clear for this prime/line.
Parameters:
Parameters
m_id int matrix identifier (-1 for iZm5, 1 for iZm7).
p Unsigned 64-bit integer parameter.
vx Size_t parameter representing the vx value.
y mpz_t parameter representing the y value.
Returns
The computed x value as a 64-bit unsigned integer.
Definition at line 449 of file iZ_toolkit.c.
Referenced by vx_det_sieve(), and vx_search_prime().
iZm_solve_for_y0()
int64_t iZm_solve_for_y0 (int m_id, uint64_t p, uint64_t vx, uint64_t x)
Solve first y-hit for fixed x in vertical (vy) scanning.
Compute the first composite hit of p in the xth vy segment in iZm of width vx.
Parameters
m_id Line id (-1 for x5, +1 for x7).
p Prime used for marking.
vx Segment width.
x Fixed x-coordinate.
Returns
y index on success, -1 when no modular solution exists.
Description: This function solves for the smallest y that satisfies the equation (x + vx * y) x_p (mod p), where x_p is normalized based on the m_id and p. The function checks if p and vx are co-primes, and if not, it returns -1 indicating no solution can be found. If they are co-primes, it calculates the multiplicative inverse of vx modulo p and computes y using the formula y = (delta * vx_inv) % p, where delta is the difference between x_p and x modulo p.
Parameters:
Parameters
m_id int matrix identifier (-1 for iZm5, 1 for iZm7).
p Unsigned 64-bit integer parameter.
vx Size_t parameter representing the vx value.
x Unsigned 64-bit integer parameter.
Returns
The computed y value as a 64-bit unsigned integer.
Definition at line 490 of file iZ_toolkit.c.
References gcd(), and modular_inverse().
Referenced by SiZm_vy().
process_iZ_bitmaps()
void process_iZ_bitmaps (UI64_ARRAY * primes, BITMAP * x5, BITMAP * x7, uint64_t x_limit)
Traverse iZ bitmaps, emit surviving primes, and mark composites.
Consume iZ candidate bitmaps, emit primes, and mark root composites.
Parameters
primes Output prime array.
x5 Bitmap for 6x-1 candidates.
x7 Bitmap for 6x+1 candidates.
x_limit Exclusive x upper bound.
primes Destination array for discovered primes.
x5 Bitmap for 6x-1 candidates.
x7 Bitmap for 6x+1 candidates.
x_limit Exclusive x upper bound.
Definition at line 70 of file iZ_toolkit.c.
References bitmap_clear_steps_simd(), bitmap_get_bit(), iZ(), and ui64_push().
Referenced by get_root_primes(), SiZ(), and SiZm().
range_info_free()
void range_info_free (IZM_RANGE_INFO * info)
Clear all GMP fields owned by info.
Definition at line 989 of file iZ_toolkit.c.
References IZM_RANGE_INFO::Xe, IZM_RANGE_INFO::Xs, IZM_RANGE_INFO::Ye, IZM_RANGE_INFO::Ys, IZM_RANGE_INFO::Ze, and IZM_RANGE_INFO::Zs.
Referenced by SiZ_count(), and SiZ_stream().
range_info_init()
IZM_RANGE_INFO range_info_init (INPUT_SIEVE_RANGE * input_range, int vx)
Map a decimal range input into iZm coordinates and segment bounds.
Parameters
input_range Range input (start, range).
vx iZm segment width.
Returns
Initialized range-info object; y_range < 0 indicates invalid input or an unsupported y-span for the current implementation.
Definition at line 944 of file iZ_toolkit.c.
References log_error(), INPUT_SIEVE_RANGE::range, INPUT_SIEVE_RANGE::start, IZM_RANGE_INFO::vx, IZM_RANGE_INFO::Xe, IZM_RANGE_INFO::Xs, IZM_RANGE_INFO::y_range, IZM_RANGE_INFO::Ye, IZM_RANGE_INFO::Ys, IZM_RANGE_INFO::Ze, and IZM_RANGE_INFO::Zs.
Referenced by SiZ_count(), and SiZ_stream().
vx_collect_p_gaps()
void vx_collect_p_gaps (VX_SEG * vx_obj)
Extract prime-gap encoding from a fully sieved segment.
Convert survivor bits into compact prime-gap encoding.
Parameters
vx_obj Segment object.
This routine must run after deterministic/probabilistic sieving is complete. It populates VX_SEG::p_gaps for downstream streaming and gap traversal.
Parameters
vx_obj Segment object with validated prime survivors.
Definition at line 787 of file iZ_toolkit.c.
References bitmap_get_bit(), VX_SEG::is_large_limit, VX_SEG::p_count, VX_SEG::p_gaps, VX_SEG::start_x, ui16_init(), ui16_push(), vx_full_sieve(), VX_SEG::x5, VX_SEG::x7, and VX_SEG::y.
Referenced by vx_full_sieve().
vx_free()
void vx_free (VX_SEG ** vx_obj)
Free a VX segment and all owned resources.
Free all memory owned by a VX segment object.
Parameters
vx_obj Address of a VX_SEG pointer.
vx_obj Address of the VX_SEG pointer to release.
Definition at line 759 of file iZ_toolkit.c.
References bitmap_free(), and ui16_free().
Referenced by SiZ_count(), and SiZ_stream().
vx_full_sieve()
void vx_full_sieve (VX_SEG * vx_obj, int collect_p_gaps)
Complete segment processing (probabilistic stage and optional gaps).
This function performs the sieve process on a given vx and y defined in the VX_SEG structure, and stores the primes gaps in the vx_obj->p_gaps array.
Parameters
vx_obj Segment object.
collect_p_gaps Non-zero to populate VX_SEG::p_gaps.
Description: This function combines deterministic sieving and probabilistic primality tests to identify prime candidates in a standard VX segment of a specific y in the iZ-Matrix. It could be used to only count primes in the vx segment, and optionally populates the vx_obj->p_gaps array with prime gaps between consecutive primes detected in the segment.
Parameters
vx_obj The VX_SEG to be processed.
collect_p_gaps 0 only counts primes and doesn't store prime gaps, other non-zero int values populates vx_obj->p_gaps with detected prime gaps.
Definition at line 847 of file iZ_toolkit.c.
References VX_SEG::is_large_limit, vx_collect_p_gaps(), and vx_prob_sieve().
Referenced by SiZ_count(), and vx_collect_p_gaps().
vx_init()
VX_SEG * vx_init (IZM * iZm, int start_x, int end_x, char * y_str, int mr_rounds)
Initialize and deterministically sieve one VX segment.
Initialize the members of the VX_SEG structure with the given parameters and defaults.
Parameters
iZm Initialized toolkit context.
start_x Inclusive x start index.
end_x Inclusive x end index.
y_str Segment index y as a decimal string.
mr_rounds Miller-Rabin rounds (0 uses default).
Returns
Initialized and partially processed segment, or NULL on failure.
Description: This function allocates memory for a VX_SEG structure and initializes its members. The count is initialized to 0, and the p_gaps array is allocated with an initial size of (vx/2).
Parameters:
Parameters
y_str A character pointer representing a numeric string.
Returns
VX_SEG* A pointer to the initialized VX_SEG structure. NULL if memory allocation fails or y_str is not a numeric string.
Definition at line 713 of file iZ_toolkit.c.
References IZM::base_x5, IZM::base_x7, VX_SEG::bit_ops, bitmap_clone(), VX_SEG::end_x, log_error(), MAX, MIN, MR_ROUNDS, VX_SEG::mr_rounds, VX_SEG::p_count, VX_SEG::p_gaps, VX_SEG::p_test_ops, VX_SEG::start_x, IZM::vx, VX_SEG::vx, vx_det_sieve(), vx_set_base_values(), VX_SEG::x5, and VX_SEG::x7.
Referenced by SiZ_count(), and SiZ_stream().
vx_search_prime()
int vx_search_prime (mpz_t p, int m_id, int vx, int bit_size)
Horizontal iZm/VX random-prime search.
horizontal search routine for generating a random prime.
Parameters
p Output prime.
m_id Requested line id (-1, +1, or random when other value).
vx Segment width.
bit_size Target bit size.
Returns
1 on success, otherwise 0.
Description: This function searches for a prime number using the given parameters. It combines the iZ-Matrix filtering techniques with the Miller-Rabin primality test. The search is performed by finding suitable x values that do not correspond to composites of primes that divide vx. Then, it iterates over y values in the equation p = iZ(x + vx * y) until a prime is found.
Parameters
p The prime number found in the search.
m_id The identifier (1 or -1) for the iZ matrix.
vx The horizontal vector of the iZ matrix.
bit_size The target bit size of the prime.
Returns
1 if a prime is found, 0 otherwise.
Definition at line 1017 of file iZ_toolkit.c.
References UI64_ARRAY::array, bitmap_clear_steps(), bitmap_free(), bitmap_get_bit(), bitmap_init(), check_primality(), UI64_ARRAY::count, gmp_seed_randstate(), iZ_mpz(), iZm_solve_for_x0_mpz(), log_error(), MAX, MR_ROUNDS, SiZm(), and ui64_free().
Referenced by vx_random_prime().
vx_stream()
void vx_stream (VX_SEG * vx_obj, FILE * output)
Stream segment primes to an output stream.
Stream segment primes to an output stream in traversal order.
Parameters
vx_obj Segment object.
output Writable output stream (e.g. stdout or a file).
vx_obj Segment object.
output Destination stream (stdout or file).
Definition at line 866 of file iZ_toolkit.c.
References bitmap_clear_bit(), bitmap_get_bit(), check_primality(), VX_SEG::is_large_limit, iZ_mpz(), VX_SEG::mr_rounds, VX_SEG::p_count, VX_SEG::p_test_ops, VX_SEG::start_x, VX_SEG::x5, VX_SEG::x7, and VX_SEG::yvx.
Referenced by SiZ_stream().
vy_search_prime()
int vy_search_prime (mpz_t p, int m_id, mpz_t vx)
Vertical iZm/VY random-prime search.
vertical search routine for generating a random prime.
Parameters
p Output prime.
m_id Requested line id (-1, +1, or random when other value).
vx Segment width.
Returns
1 on success, otherwise 0.
Description: This function searches for a prime number using the given parameters. It combines the iZ-Matrix filtering techniques with the Miller-Rabin primality test. The search is performed by finding a suitable x value that does not correspond to a composite of a prime that divides vx. Then, it iterates over y value in the equation p = iZ(x + vx * y, m_id) until a prime is found.
Parameters
p The prime number found in the search.
m_id The identifier (1 or -1) for the iZ matrix.
vx The horizontal vector of the iZ matrix.
Returns
1 if a prime is found, 0 otherwise.
Definition at line 1114 of file iZ_toolkit.c.
References check_primality(), gmp_seed_randstate(), iZ_mpz(), and MR_ROUNDS.
Referenced by vy_random_prime().