iZ-Library: Logging
Logging
Thread-safe runtime logging helpers.
Files
file logger.c
Logging module.
Macros
#define LOGGER_FORMAT_PRINTF(fmt_idx, arg_idx)
Compiler attribute wrapper for printf-style format checking.
#define LOG_DIR "logs/"
Directory where logs are stored.
#define LOG_FILE LOG_DIR "log.txt"
Default log file.
#define LOG_MAX_SIZE 1024 * 1024 * 5
Maximum log file size (5 MB).
Enumerations
enum LogLevel {
LOG_DEBUG , LOG_INFO , LOG_WARNING , LOG_ERROR ,
LOG_FATAL
}
Enumeration of log levels.
Functions
const char * log_level_to_string (LogLevel level)
Returns a string representation of the log level.
void log_init (const char *log_file)
Initializes the logging system.
void log_shutdown (void)
Shuts down the logging system and cleans up resources.
void log_set_log_level (LogLevel level)
Sets the current log level. Messages below this level will not be logged.
void log_message (LogLevel level, const char *format,...) LOGGER_FORMAT_PRINTF(2
Logs a formatted message at the given log level.
void void log_message_extended (LogLevel level, const char *file_name, int line_number, const char *format,...) LOGGER_FORMAT_PRINTF(4
Logs a formatted message with extended information (file name, line number).
void void void log_console (const char *format,...) LOGGER_FORMAT_PRINTF(1
Logs a timestamped message to the console only, without requiring a log level.
void void void void log_debug (const char *format,...) LOGGER_FORMAT_PRINTF(1
Logs a debug message.
void void void void void log_info (const char *format,...) LOGGER_FORMAT_PRINTF(1
Logs an info message.
void void void void void void log_warn (const char *format,...) LOGGER_FORMAT_PRINTF(1
Logs a warning message.
void void void void void void void log_error (const char *format,...) LOGGER_FORMAT_PRINTF(1
Logs an error message.
void void void void void void void void log_fatal (const char *format,...) LOGGER_FORMAT_PRINTF(1
Logs a fatal message.
Detailed Description
Thread-safe runtime logging helpers.
Macro Definition Documentation
LOG_DIR
#define LOG_DIR "logs/"
Directory where logs are stored.
Definition at line 54 of file logger.h.
LOG_FILE
#define LOG_FILE LOG_DIR "log.txt"
Default log file.
Definition at line 55 of file logger.h.
LOG_MAX_SIZE
#define LOG_MAX_SIZE 1024 * 1024 * 5
Maximum log file size (5 MB).
Definition at line 56 of file logger.h.
LOGGER_FORMAT_PRINTF
#define LOGGER_FORMAT_PRINTF (fmt_idx, arg_idx)
Compiler attribute wrapper for printf-style format checking.
Definition at line 50 of file logger.h.
Referenced by log_console(), log_debug(), log_error(), log_fatal(), log_info(), log_message(), log_message_extended(), and log_warn().
Enumeration Type Documentation
LogLevel
enum LogLevel
Enumeration of log levels.
This enumeration defines the different log levels that can be used in the logging system. Each level corresponds to a severity of importance.
Enumerator
LOG_DEBUG
Debug level.
LOG_INFO
Info level.
LOG_WARNING
Warning level.
LOG_ERROR
Error level.
LOG_FATAL
Fatal level.
Definition at line 65 of file logger.h.
Function Documentation
log_console()
void void void log_console (const char * format, ...)
Logs a timestamped message to the console only, without requiring a log level.
This can be used for debugging or tracking specific points in the code.
Parameters
format The format string for the log message.
References log_console(), and LOGGER_FORMAT_PRINTF.
Referenced by log_console().
log_debug()
void void void void log_debug (const char * format, ...)
Logs a debug message.
Parameters
format The format string for the log message.
References log_debug(), and LOGGER_FORMAT_PRINTF.
Referenced by iZ_next_prime(), and log_debug().
log_error()
void void void void void void void log_error (const char * format, ...)
Logs an error message.
Parameters
format The format string for the log message.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
References log_error(), and LOGGER_FORMAT_PRINTF.
Referenced by bitmap_fread(), bitmap_fwrite(), bitmap_init(), bitmap_validate_hash(), create_dir(), iZ_next_prime(), iZm_clone(), iZm_init(), log_error(), range_info_init(), SiZ_count(), SiZ_stream(), vx_init(), vx_random_prime(), vx_search_prime(), vx_set_base_values(), and vy_random_prime().
log_fatal()
void void void void void void void void log_fatal (const char * format, ...)
Logs a fatal message.
Parameters
format The format string for the log message.
References log_fatal(), and LOGGER_FORMAT_PRINTF.
Referenced by log_fatal().
log_info()
void void void void void log_info (const char * format, ...)
Logs an info message.
Parameters
format The format string for the log message.
References log_info(), and LOGGER_FORMAT_PRINTF.
Referenced by log_info(), and vx_prob_sieve().
log_init()
void log_init (const char * log_file)
Initializes the logging system.
Creates the log directory if it doesn't exist and rotates logs if necessary.
Parameters
log_file The path to the log file.
log_level_to_string()
const char * log_level_to_string (LogLevel level)
Returns a string representation of the log level.
Parameters
level The log level.
Returns
A string corresponding to the log level.
log_message()
void log_message (LogLevel level, const char * format, ...)
Logs a formatted message at the given log level.
This function logs messages to the log file in a thread-safe manner.
Parameters
level The log level for the message.
format The format string for the log message.
References LOGGER_FORMAT_PRINTF.
log_message_extended()
void void log_message_extended (LogLevel level, const char * file_name, int line_number, const char * format, ...)
Logs a formatted message with extended information (file name, line number).
This function logs messages to the log file in a thread-safe manner.
Parameters
level The log level for the message.
file_name The source file where the log was generated.
line_number The line number in the source file.
format The format string for the log message.
References log_message_extended(), and LOGGER_FORMAT_PRINTF.
Referenced by log_message_extended().
log_set_log_level()
void log_set_log_level (LogLevel level)
Sets the current log level. Messages below this level will not be logged.
Parameters
level The log level to set.
log_warn()
void void void void void void log_warn (const char * format, ...)
Logs a warning message.
Parameters
format The format string for the log message.
References log_warn(), and LOGGER_FORMAT_PRINTF.
Referenced by log_warn().