iZ-Library: Utilities
Utilities
Cross-cutting helpers used across modules.
Files
file utils.c
Implementations for the shared utility layer.
Macros
#define MIN(a, b)
Return the smaller of two expressions.
#define MAX(a, b)
Return the larger of two expressions.
#define DIR_output "./output"
#define MAX_CORES get_cpu_cores_count()
Functions
int create_dir (const char *dir)
Create a directory if it does not exist.
int is_numeric_str (const char *str)
Return non-zero if str contains only ASCII digits.
int parse_numeric_expr_mpz (mpz_t out, const char *expr)
Parse an integer expression into an mpz value.
int parse_numeric_expr_u64 (const char *expr, uint64_t *out)
Parse an integer expression into uint64_t.
int parse_inclusive_range_mpz (const char *range_expr, mpz_t lower, mpz_t upper)
Parse an inclusive range expression into lower/upper bounds.
uint64_t gcd (uint64_t a, uint64_t b)
Compute the greatest common divisor of a and b.
uint64_t modular_inverse (uint64_t a, uint64_t m)
Compute the modular inverse of a modulo m.
void gmp_seed_randstate (gmp_randstate_t state)
Seed a GMP random state.
int get_cpu_cores_count (void)
Get the number of online CPU cores (>= 1).
int get_cpu_L2_cache_size_bits (void)
Return the CPU L2 cache size in bits (best effort).
Detailed Description
Cross-cutting helpers used across modules.
Macro Definition Documentation
DIR_output
#define DIR_output "./output"
Default directory for output artifacts produced by examples/tests.
Definition at line 56 of file utils.h.
MAX
#define MAX (a, b)
Value:
(((a) > (b)) ? (a) : (b))
Return the larger of two expressions.
Definition at line 52 of file utils.h.
Referenced by SiZ_stream(), SSoE(), vx_init(), vx_random_prime(), vx_search_prime(), and vy_random_prime().
MAX_CORES
#define MAX_CORES get_cpu_cores_count()
Convenience macro: number of online CPU cores.
Definition at line 58 of file utils.h.
MIN
#define MIN (a, b)
Value:
(((a) < (b)) ? (a) : (b))
Return the smaller of two expressions.
Examples
/Users/hazemmounir/Workspace/iZproject/iZprime/src/toolkit/bitmap.c.
Definition at line 48 of file utils.h.
Referenced by bitmap_clear_steps(), bitmap_clear_steps_simd(), compute_l2_vx(), SiZ_count(), SiZ_stream(), and vx_init().
Function Documentation
create_dir()
int create_dir (const char * dir)
Create a directory if it does not exist.
Parameters
dir Directory path.
Returns
0 on success (including already exists), -1 on failure.
Parameters
dir The directory path.
Returns
int 0 if the directory already exists or was successfully created, -1 otherwise.
Definition at line 402 of file utils.c.
References log_error().
gcd()
uint64_t gcd (uint64_t a, uint64_t b)
Compute the greatest common divisor of a and b.
Compute the greatest common divisor of a and b.
Parameters
a The first integer.
b The second integer.
Returns
int The GCD of a and b.
Definition at line 425 of file utils.c.
Referenced by iZm_solve_for_y0(), and SiZm_vy().
get_cpu_cores_count()
int get_cpu_cores_count (void)
Get the number of online CPU cores (>= 1).
Get the number of online CPU cores (>= 1).
Returns
int The number of CPU cores.
Definition at line 509 of file utils.c.
Referenced by SiZ_count().
get_cpu_L2_cache_size_bits()
int get_cpu_L2_cache_size_bits (void)
Return the CPU L2 cache size in bits (best effort).
Returns
Cache size in bits, or a conservative default.
Return the CPU L2 cache size in bits (best effort).
Description: This function retrieves the L2 cache size using platform-specific methods:
Linux: Reads from sysfs (/sys/devices/system/cpu/cpu0/cache/index2/size)
macOS/BSD: Uses sysctl to query hw.l2cachesize
Fallback: Returns 256 Kbits as a conservative default
The function attempts multiple detection methods to ensure robustness across different architectures and operating systems.
Returns
int The L2 cache size in bits, or 256 Kbits if unable to determine.
Definition at line 531 of file utils.c.
Referenced by compute_l2_vx().
gmp_seed_randstate()
void gmp_seed_randstate (gmp_randstate_t state)
Seed a GMP random state.
Attempts to seed from /dev/urandom, falling back to time-based seeding.
Seed a GMP random state.
Description: This function seeds the GMP random state using /dev/urandom.
Parameters
state The GMP random state.
Definition at line 486 of file utils.c.
Referenced by vx_search_prime(), and vy_search_prime().
is_numeric_str()
int is_numeric_str (const char * str)
Return non-zero if str contains only ASCII digits.
Parameters
str Input string.
Returns
1 if numeric, 0 otherwise.
Return non-zero if str contains only ASCII digits.
Parameters
str Pointer to the string.
Returns
int 1 if the string is numeric, 0 otherwise.
Definition at line 258 of file utils.c.
modular_inverse()
uint64_t modular_inverse (uint64_t a, uint64_t m)
Compute the modular inverse of a modulo m.
Returns
The inverse in [0, m-1] if it exists; otherwise an implementation-defined value.
Compute the modular inverse of a modulo m.
Description: This function computes the modular inverse of a modulo m using the Extended Euclidean Algorithm. The function takes two integers a and m as input and returns the modular inverse of a modulo m. If a and m are not co-prime, the function returns -1 indicating no modular inverse exists. The function also handles the case where m is 1, returning 0 as the modular inverse.
Parameters:
Parameters
a The integer for which the modular inverse is to be computed.
m The modulus.
Returns
The modular inverse of a modulo m, or -1 if no inverse exists.
Definition at line 453 of file utils.c.
Referenced by iZm_solve_for_y0().
parse_inclusive_range_mpz()
int parse_inclusive_range_mpz (const char * range_expr, mpz_t lower, mpz_t upper)
Parse an inclusive range expression into lower/upper bounds.
Accepted forms:
L,R
[L, R]
range[L, R]
L..R
L:R
Each bound accepts the same numeric formats as parse_numeric_expr_mpz.
Parameters
range_expr Range expression string.
lower Output lower bound.
upper Output upper bound.
Returns
1 on success, 0 on parse failure.
Definition at line 335 of file utils.c.
parse_numeric_expr_mpz()
int parse_numeric_expr_mpz (mpz_t out, const char * expr)
Parse an integer expression into an mpz value.
Supported term formats:
plain decimal integer (1000000, 1,000,000)
power notation (10^6)
scientific shorthand (1e6, 10e100)
additive expressions (10e100 + 10e9)
Parameters
out Output mpz value.
expr Input expression string.
Returns
1 on success, 0 on parse failure.
Definition at line 272 of file utils.c.
Referenced by parse_numeric_expr_u64().
parse_numeric_expr_u64()
int parse_numeric_expr_u64 (const char * expr, uint64_t * out)
Parse an integer expression into uint64_t.
Parameters
expr Input expression string.
out Output value.
Returns
1 on success, 0 on parse failure or overflow.
Definition at line 314 of file utils.c.
References parse_numeric_expr_mpz().