iZ-Library: Printer, implemented in toolkit/print_utils.c
Printer, implemented in toolkit/print_utils.c
Console formatting helpers used by tests and benchmark runners.
Files
file print_utils.c
Print formatting helpers for tests, benchmarks, and CLI output.
Functions
void print_sha256_hash (const unsigned char *hash)
Print a SHA-256 digest as hex to stdout.
void print_line (int length, char fill_char)
Print a repeated-character horizontal line.
void print_centered_text (const char *text, int line_length, char fill_char)
Print text centered inside a padded line.
void print_test_table_header (void)
Print the generic test runner header.
void print_test_module_header (char *module_name)
Print a test-suite header banner for a module.
void print_test_fn_header (char *fn_name)
Print a formatted header for a test function.
void print_test_module_result (int result, int test_id, const char *unit_name, const char *format,...)
Print a single test-row result.
void print_test_summary (char *module_name, int passed, int failed, int verbose)
Print module-level test summary.
Detailed Description
Console formatting helpers used by tests and benchmark runners.
Function Documentation
print_centered_text()
void print_centered_text (const char * text, int line_length, char fill_char)
Print text centered inside a padded line.
Print centered text within a line of specified length.
Parameters
text Text payload.
line_length Target total line width.
fill_char Padding character.
text Text to center.
line_length Total length of the line.
fill_char Character to use for padding (' ' is used when zero).
Definition at line 30 of file print_utils.c.
Referenced by print_test_fn_header().
print_line()
void print_line (int length, char fill_char)
Print a repeated-character horizontal line.
Parameters
length Number of characters to print.
fill_char Character to repeat ('-' is used when zero).
Definition at line 14 of file print_utils.c.
Referenced by print_test_fn_header(), print_test_module_header(), print_test_summary(), and print_test_table_header().
print_sha256_hash()
void print_sha256_hash (const unsigned char * hash)
Print a SHA-256 digest as hex to stdout.
Print the SHA-256 hash in hexadecimal format.
Parameters
hash Pointer to the SHA-256 hash array.
Definition at line 58 of file print_utils.c.
print_test_fn_header()
void print_test_fn_header (char * fn_name)
Print a formatted header for a test function.
Definition at line 148 of file print_utils.c.
References print_centered_text(), and print_line().
print_test_module_header()
void print_test_module_header (char * module_name)
Print a test-suite header banner for a module.
Print module-level banner for test output.
Parameters
module_name Display name of the tested module.
Definition at line 70 of file print_utils.c.
References print_line().
print_test_module_result()
void print_test_module_result (int result, int test_id, const char * unit_name, const char * format, ...)
Print a single test-row result.
Print a single test unit result row with formatted details.
Parameters
result 1 for pass, 0 for fail.
test_id Monotonic case index.
unit_name Short test unit label.
format printf-style detail format.
result 1 for pass, 0 for fail.
test_id Monotonic case index.
unit_name Short test unit label.
format printf-style detail format string.
... Arguments for the detail format string.
Definition at line 96 of file print_utils.c.
print_test_summary()
void print_test_summary (char * module_name, int passed, int failed, int verbose)
Print module-level test summary.
Print a summary of test results for a module.
Parameters
module_name Test module name.
passed Number of passing tests.
failed Number of failing tests.
verbose Non-zero enables richer output hints.
module_name Name of the tested module.
passed Number of passing tests.
failed Number of failing tests.
verbose If non-zero, prints additional hints about the results.
Definition at line 126 of file print_utils.c.
References print_line().
print_test_table_header()
void print_test_table_header (void)
Print the generic test runner header.
Print standard test-table column headers.
Definition at line 80 of file print_utils.c.
References print_line().