iZ-Library: Printer
Printer
Console formatting helpers used by tests and benchmark runners.
Files
file printer.c
Console formatting helpers for tests and benchmarks.
Functions
void print_line (int length, char fill_char)
Print a repeated-character horizontal line.
void print_centered_text (const char *text, int line_length, char fill_char)
Print text centered inside a padded line.
void log_test (int result, int test_id, const char *unit_name, const char *format,...)
Print a single test-row result.
void log_test_summary (char *module_name, int passed, int failed, int verbose)
Print module-level test summary.
Detailed Description
Console formatting helpers used by tests and benchmark runners.
Function Documentation
log_test()
void log_test (int result, int test_id, const char * unit_name, const char * format, ...)
Print a single test-row result.
Parameters
result 1 for pass, 0 for fail.
test_id Monotonic case index.
unit_name Short test unit label.
format printf-style detail format.
Definition at line 43 of file printer.c.
log_test_summary()
void log_test_summary (char * module_name, int passed, int failed, int verbose)
Print module-level test summary.
Parameters
module_name Test module name.
passed Number of passing tests.
failed Number of failing tests.
verbose Non-zero enables richer output hints.
Definition at line 65 of file printer.c.
References print_line().
print_centered_text()
void print_centered_text (const char * text, int line_length, char fill_char)
Print text centered inside a padded line.
Parameters
text Text payload.
line_length Target total line width.
fill_char Padding character.
Definition at line 20 of file printer.c.
print_line()
void print_line (int length, char fill_char)
Print a repeated-character horizontal line.
Parameters
length Number of characters to print.
fill_char Character to repeat ('-' is used when zero).
Definition at line 10 of file printer.c.
Referenced by log_test_summary(), print_module_header(), and print_test_header().