iZ-Library: iZ Public API
iZ Public API
< iZ/iZm toolkit structures and helpers.
Files
file iZ_apps.c
High-level application routines built on top of the iZ_toolkit.
file prime_sieve.c
Implementations of classical and SiZ-family sieve algorithms.
Data Structures
struct INPUT_SIEVE_RANGE
Input parameters for range sieving/counting.
SiZ Range Variants
Count/stream primes over a numeric interval.
typedef struct INPUT_SIEVE_RANGE INPUT_SIEVE_RANGE
Input parameters for range sieving/counting.
uint64_t SiZ_stream (INPUT_SIEVE_RANGE *range)
Stream primes in a range to filepath (and return the count).
uint64_t SiZ_count (INPUT_SIEVE_RANGE *input_range, int cores_num)
Count primes in a range using multiple worker processes.
Classic Prime Sieve Algorithms
Baseline sieves up to a numeric limit.
All classic sieve functions take a limit n and return an ascending list of primes <= n.
UI64_ARRAY * SoE (uint64_t n)
Optimized Sieve of Eratosthenes.
UI64_ARRAY * SSoE (uint64_t n)
Segmented Sieve of Eratosthenes.
UI64_ARRAY * SoEu (uint64_t n)
Euler (linear) sieve.
UI64_ARRAY * SoS (uint64_t n)
Sieve of Sundaram.
UI64_ARRAY * SoA (uint64_t n)
Sieve of Atkin.
iZ-based Sieve Algorithms
Sieve family operating in the 6x-1 / 6x+1 index space.
UI64_ARRAY * SiZ (uint64_t n)
Solid Sieve-iZ (wheel 6, iZ index space).
UI64_ARRAY * SiZm (uint64_t n)
Segmented Sieve-iZm (VX segmented, horizontal processing).
UI64_ARRAY * SiZm_vy (uint64_t n)
Segmented Sieve-iZm (vertical processing; faster, unordered output).
Prime Generators
Probabilistic prime searches using iZm/VX machinery.
int vy_random_prime (mpz_t p, int bit_size, int cores_num)
Search for a random prime using vertical (vy) sieving.
int vx_random_prime (mpz_t p, int bit_size, int cores_num)
Search for a random prime using horizontal (vx) sieving.
int iZ_next_prime (mpz_t p, mpz_t base, int forward)
Advance to the next (or previous) prime from a base value.
Detailed Description
< iZ/iZm toolkit structures and helpers.
< Common utilities, types, and dependencies.
High-level entry points for sieves and prime generation.
The API is organized into:
Classic sieves: operate directly on the integer domain.
SiZ / SiZm: operate in iZ index space (6x-1 and 6x+1), optionally segmented.
Range variants: count/stream primes over large intervals.
Prime generators: probabilistic searches using the iZm/VX machinery.
Typedef Documentation
INPUT_SIEVE_RANGE
typedef struct INPUT_SIEVE_RANGE INPUT_SIEVE_RANGE
Input parameters for range sieving/counting.
The interval is interpreted as:
Start $Z_s$ from the decimal string start.
End $Z_e = Z_s + range - 1$.
Forward declaration; concrete definition lives in iZ_api.h.
Function Documentation
iZ_next_prime()
int iZ_next_prime (mpz_t p, mpz_t base, int forward)
Advance to the next (or previous) prime from a base value.
Find the next prime number after a given base.
Parameters
p Output prime (initialized by caller).
base Starting value.
forward Non-zero to search forward, 0 to search backward.
Returns
1 on success, 0 on failure.
Description: This function searches for the next/previous prime number after a given base using the iZ framework.
Parameters
p The mpz_t variable to store the found prime number.
base The base number to start the search from.
forward If true, search for the next prime; if false, search for the previous prime.
Returns
1 if a prime is found, 0 otherwise.
Definition at line 819 of file iZ_apps.c.
References IZM::base_x5, IZM::base_x7, bitmap_get_bit(), iZ_mpz(), iZm_free(), iZm_init(), log_debug(), log_error(), MR_ROUNDS, VX5, and VX6.
SiZ()
UI64_ARRAY * SiZ (uint64_t n)
Solid Sieve-iZ (wheel 6, iZ index space).
Classic Sieve-iZ algorithm for prime generation up to n.
Parameters
n Upper bound (inclusive).
Returns
Heap-allocated prime list, or NULL on allocation failure.
Precondition
n is in (10, 10^12].
The Sieve-iZ algorithm operates in the iZ index space of numbers of the form 6x ± 1, excluding all multiples of 2 and 3. It maintains two bitmaps, x5 and x7, representing candidates of the form 6x − 1 (iZ−) and 6x + 1 (iZ+), respectively. For each index x whose bit remains set, the corresponding candidate is treated as prime and its composites are marked using the Xp identity in the iZ space.
This provides a wheel factorization of modulo 6, reducing the number of candidates by approximately a factor of 3 compared to a classical sieve over all integers. After sieving, any remaining set bits correspond to primes of the form 6x ± 1, which are mapped back to their integer values and appended to the output array alongside the primes 2 and 3.
Parameters
n Upper bound (inclusive) for prime generation. Must satisfy 10 < n <= pow(10, 12).
Returns
Pointer to a UI64_ARRAY containing all primes <= n on success, or NULL if allocation fails.
Definition at line 444 of file prime_sieve.c.
References UI64_ARRAY::array, ASSERT_LIMIT, bitmap_free(), bitmap_init(), UI64_ARRAY::count, Pi, process_iZ_bitmaps(), ui64_free(), ui64_init(), ui64_pop(), ui64_push(), and ui64_resize_to_fit().
Referenced by compute_max_vx(), iZm_init(), SiZm(), and SiZm_vy().
SiZ_count()
uint64_t SiZ_count (INPUT_SIEVE_RANGE * input_range, int cores_num)
Count primes in a range using multiple worker processes.
Multi-process prime counting over an arbitrary numeric range using iZ toolkit.
Parameters
input_range Range configuration (output disabled).
cores_num Requested worker process count.
Returns
Prime count in the interval, or 0 on error.
This function parallelizes prime counting over the interval [Zs, Ze] (interpreted from input_range) by partitioning the corresponding iZ index space into VX segments and distributing contiguous blocks of segments across multiple processes. Each child process returns a local prime count to the parent via a pipe.
The parent process aggregates all child counts, applies boundary corrections for endpoints that do not align exactly with 6x ± 1, and returns the total number of primes in [Zs, Ze]. Any failure to create pipes, fork children, or initialize per-process resources causes the function to log an error and return 0.
Parameters
input_range Pointer to an INPUT_SIEVE_RANGE structure describing the numeric interval and Miller–Rabin configuration.
cores_num Requested number of worker processes. The actual number used is clamped to the available CPU cores and the number of VX segments in the range.
Returns
The total number of primes found in [Zs, Ze] on success, or 0 on any error or child-process failure.
Definition at line 184 of file iZ_apps.c.
References UI64_ARRAY::array, compute_l2_vx(), UI64_ARRAY::count, get_cpu_cores_count(), iZ_mpz(), iZm_clone(), iZm_free(), iZm_init(), log_error(), MIN, INPUT_SIEVE_RANGE::mr_rounds, VX_SEG::p_count, INPUT_SIEVE_RANGE::range, range_info_free(), range_info_init(), SiZm(), INPUT_SIEVE_RANGE::start, ui64_free(), vx_free(), vx_full_sieve(), vx_init(), IZM_RANGE_INFO::Xe, IZM_RANGE_INFO::Xs, IZM_RANGE_INFO::y_range, IZM_RANGE_INFO::Ye, IZM_RANGE_INFO::Ys, IZM_RANGE_INFO::Ze, and IZM_RANGE_INFO::Zs.
SiZ_stream()
uint64_t SiZ_stream (INPUT_SIEVE_RANGE * input_range)
Stream primes in a range to filepath (and return the count).
Stream primes in an arbitrary numeric range using iZ toolkit.
Parameters
range Range configuration (must include filepath).
Returns
Prime count in the interval, or 0 on error.
This function counts and streams primes in the interval [Zs, Ze] defined by the input range. It maps the numeric bounds into the iZ index space (6x ± 1), partitions that space into y segments of length vx, and streams primes in each segment using the iZ toolkit.
When an output file path is provided in input_range->filepath, the function additionally streams all primes in the requested interval to that file in ascending order, reconstructing them from per-segment prime gaps. Otherwise, it operates in counting mode only.
Parameters
input_range Pointer to an INPUT_SIEVE_RANGE structure describing the start value (as a decimal string), the range length, the optional output filepath, and Miller–Rabin configuration.
Returns
The total number of primes found in [Zs, Ze] on success, or 0 on invalid input, allocation failure, or I/O error.
Definition at line 35 of file iZ_apps.c.
References UI64_ARRAY::array, UI64_ARRAY::count, INPUT_SIEVE_RANGE::filepath, iZm_free(), iZm_init(), log_error(), MAX, MIN, INPUT_SIEVE_RANGE::mr_rounds, VX_SEG::p_count, range_info_free(), range_info_init(), SiZm(), INPUT_SIEVE_RANGE::start, ui64_free(), IZM_RANGE_INFO::vx, VX6, vx_free(), vx_init(), vx_stream(), IZM_RANGE_INFO::Xe, IZM_RANGE_INFO::Xs, IZM_RANGE_INFO::y_range, IZM_RANGE_INFO::Ye, IZM_RANGE_INFO::Ys, IZM_RANGE_INFO::Ze, and IZM_RANGE_INFO::Zs.
SiZm()
UI64_ARRAY * SiZm (uint64_t n)
Segmented Sieve-iZm (VX segmented, horizontal processing).
Segmented Sieve-iZm algorithm for prime generation up to n.
Parameters
n Upper bound (inclusive).
Returns
Heap-allocated prime list, or NULL on allocation failure.
Precondition
n is in (10, 10^12].
Description: The Sieve-iZm algorithm is a segmented, cache-aware variant of the Sieve-iZ that operates in the iZ index space of numbers of the form 6x ± 1. It partitions the search interval into segments of length vx, where vx is a product of small primes, and constructs a pre-sieved base segment using those small primes once at initialization time.
For each segment, Sieve-iZm clones the base bitmaps and only marks composites of the remaining root primes that do not divide vx. This amortizes the cost of small-prime sieving across all segments and keeps the working set small and highly cache-resident. After marking, any remaining set bits correspond to primes of the form 6x ± 1 within that segment, which are then mapped back to their integer values and appended to the output array.
Compared to the basic Sieve-iZ, Sieve-iZm achieves the same O(n log log n) time complexity with effectively constant auxiliary memory (aside from the output) and significantly reduced constant factors, making it well-suited for enumerating primes up to large bounds.
Parameters
n Upper bound (inclusive) for prime generation. Must satisfy 10 < n <= pow(10, 12).
Returns
Pointer to a UI64_ARRAY containing all primes <= n on success, or NULL on allocation or initialization failure.
Definition at line 516 of file prime_sieve.c.
References UI64_ARRAY::array, ASSERT_LIMIT, bitmap_clear_steps_simd(), bitmap_clone(), bitmap_free(), bitmap_get_bit(), bitmap_init(), BITMAP::byte_size, compute_l2_vx(), UI64_ARRAY::count, BITMAP::data, iZ(), iZm_construct_vx_base(), iZm_solve_for_x0(), Pi, process_iZ_bitmaps(), SiZ(), ui64_free(), ui64_init(), ui64_pop(), ui64_push(), and ui64_resize_to_fit().
Referenced by SiZ_count(), SiZ_stream(), and vx_search_prime().
SiZm_vy()
UI64_ARRAY * SiZm_vy (uint64_t n)
Segmented Sieve-iZm (vertical processing; faster, unordered output).
Segmented Sieve-iZm with vertical (vy) traversal order.
This variant emphasizes throughput and may not preserve ascending order of returned primes.
Parameters
n Upper bound (inclusive).
Returns
Heap-allocated prime list, or NULL on allocation failure.
Precondition
n is in (10, 10^12].
This variant prioritizes throughput and returns primes in non-sorted order.
Parameters
n Inclusive upper bound for prime generation.
Returns
Heap-allocated list of primes <= n, or NULL on failure.
Definition at line 623 of file prime_sieve.c.
References UI64_ARRAY::array, ASSERT_LIMIT, bitmap_clear_steps_simd(), bitmap_free(), bitmap_get_bit(), bitmap_init(), bitmap_set_all(), UI64_ARRAY::count, gcd(), get_root_primes(), iZ(), iZm_solve_for_y0(), UI64_ARRAY::ordered, Pi, SiZ(), ui64_init(), ui64_push(), and ui64_resize_to_fit().
SoA()
UI64_ARRAY * SoA (uint64_t n)
Sieve of Atkin.
Sieve of Atkin: Generates a list of prime numbers up to a given limit using the Sieve of Atkin algorithm.
Parameters
n Upper bound (inclusive).
Returns
Heap-allocated prime list, or NULL on allocation failure.
Precondition
n is in (10, 10^12].
Description: This function implements the Sieve of Atkin, a modern algorithm to find all prime numbers up to a specified integer n. It initializes a bitmap to mark potential primes and applies the Atkin conditions to identify primes. The function also marks odd multiples of squares of primes as non-prime, then collects the remaining unmarked numbers as primes.
Parameters
n The upper limit (inclusive) up to which prime numbers are to be found.
Returns
UI64_ARRAY* A pointer to the UI64_ARRAY structure containing the list of primes up to n.
NULL if memory allocation fails or if n is less than 10.
Definition at line 328 of file prime_sieve.c.
References ASSERT_LIMIT, bitmap_clear_steps_simd(), bitmap_flip_bit(), bitmap_free(), bitmap_get_bit(), bitmap_init(), Pi, ui64_free(), ui64_init(), ui64_push(), and ui64_resize_to_fit().
SoE()
UI64_ARRAY * SoE (uint64_t n)
Optimized Sieve of Eratosthenes.
Optimized Sieve of Eratosthenes algorithm to find all primes up to n.
Parameters
n Upper bound (inclusive).
Returns
Heap-allocated prime list, or NULL on allocation failure.
Precondition
n is in (10, 10^12].
Description: This function applies common speedups to the Sieve of Eratosthenes algorithm. It works the same way as the classic sieve but skips checking or marking even numbers and starts with 3, incrementing by 2, it also starts the sieve from p*p.
Parameters
n The upper limit to find primes.
Returns
A pointer to a UI64_ARRAY structure containing the list of prime numbers up to n,
NULL if memory allocation fails or if n is less than 10.
Definition at line 72 of file prime_sieve.c.
References ASSERT_LIMIT, bitmap_free(), bitmap_init(), Pi, process_N_bitmap(), ui64_free(), ui64_init(), and ui64_resize_to_fit().
SoEu()
UI64_ARRAY * SoEu (uint64_t n)
Euler (linear) sieve.
Sieve of Euler: Generates a list of prime numbers up to a given limit using the Euler Sieve algorithm.
Parameters
n Upper bound (inclusive).
Returns
Heap-allocated prime list, or NULL on allocation failure.
Precondition
n is in (10, 10^12].
Description: This function uses the Euler Sieve algorithm to find all prime numbers up to a specified limit n. It marks each composite only once, allowing for a more efficient sieve process. It initializes a bitmap to track prime numbers and iterates through the numbers, marking distinct multiples of each prime found. The function also handles memory allocation and resizing of the primes array as needed.
Parameters
n The upper limit up to which prime numbers are to be found.
Returns
UI64_ARRAY* A pointer to the UI64_ARRAY structure containing the list of primes up to n.
NULL if memory allocation fails or if n is less than 10.
Definition at line 200 of file prime_sieve.c.
References UI64_ARRAY::array, ASSERT_LIMIT, bitmap_clear_bit(), bitmap_free(), bitmap_get_bit(), bitmap_init(), UI64_ARRAY::count, Pi, ui64_free(), ui64_init(), ui64_push(), and ui64_resize_to_fit().
SoS()
UI64_ARRAY * SoS (uint64_t n)
Sieve of Sundaram.
Sieve of Sundaram: Generates a list of prime numbers up to a given limit using the Sieve of Sundaram algorithm.
Parameters
n Upper bound (inclusive).
Returns
Heap-allocated prime list, or NULL on allocation failure.
Precondition
n is in (10, 10^12].
Description: This function implements the Sieve of Sundaram algorithm to find all prime numbers up to a specified limit n. The Sieve of Sundaram works by eliminating numbers of the form i + j + 2ij from a list of integers from 1 to k = (n-1)/2. If an integer x in this range is not eliminated, then 2x+1 is a prime number. The prime number 2 is handled as a special case, as the sieve only generates odd primes.
Parameters
n The upper limit (inclusive) up to which prime numbers are to be found.
Returns
UI64_ARRAY* A pointer to the UI64_ARRAY structure containing the list of primes up to n.
NULL if memory allocation fails or if n is less than 10.
Definition at line 264 of file prime_sieve.c.
References ASSERT_LIMIT, bitmap_clear_steps_simd(), bitmap_free(), bitmap_get_bit(), bitmap_init(), Pi, ui64_free(), ui64_init(), ui64_push(), and ui64_resize_to_fit().
SSoE()
UI64_ARRAY * SSoE (uint64_t n)
Segmented Sieve of Eratosthenes.
Segmented Sieve of Eratosthenes algorithm to find all primes up to n.
Parameters
n Upper bound (inclusive).
Returns
Heap-allocated prime list, or NULL on allocation failure.
Precondition
n is in (10, 10^12].
Description: This function implements the Segmented Sieve of Eratosthenes algorithm to find all prime numbers up to a given limit n. It divides the range into segments and uses a bitmap to mark prime numbers in each segment. The function returns a pointer to a UI64_ARRAY structure containing the list of prime numbers found. The function also handles memory allocation and resizing of the primes array as needed.
Parameters
n The upper limit to find primes.
Returns
A pointer to the UI64_ARRAY structure containing the list of primes up to n,
NULL if memory allocation fails or if n is less than 1000.
Definition at line 114 of file prime_sieve.c.
References UI64_ARRAY::array, ASSERT_LIMIT, bitmap_clear_steps_simd(), bitmap_free(), bitmap_get_bit(), bitmap_init(), bitmap_set_all(), UI64_ARRAY::count, MAX, Pi, process_N_bitmap(), ui64_free(), ui64_init(), ui64_push(), and ui64_resize_to_fit().
vx_random_prime()
int vx_random_prime (mpz_t p, int bit_size, int cores_num)
Search for a random prime using horizontal (vx) sieving.
Generates a random prime candidate using the vx_search_prime routine.
Parameters
p Output prime (initialized by caller).
bit_size Target size of p in bits.
cores_num Requested worker processes.
Returns
1 on success, 0 on failure.
Description: This function generates a random prime of a given bit size using the vx_search_prime routine. It initializes the random base and sets up the search parameters. The function also allows for parallel processing of the search using multiple child processes. The generated prime is stored in the provided mpz_t p variable.
Parameters
p The mpz_t variable to store the generated prime number.
bit_size The target bit size of the prime.
cores_num The number of cores to use for parallel processing.
Returns
1 if a prime is found, 0 otherwise.
Definition at line 692 of file iZ_apps.c.
References log_error(), MAX, VX5, VX6, and vx_search_prime().
vy_random_prime()
int vy_random_prime (mpz_t p, int bit_size, int cores_num)
Search for a random prime using vertical (vy) sieving.
Generates a random prime candidate using the vy_search_prime routine.
Parameters
p Output prime (initialized by caller).
bit_size Target size of p in bits.
cores_num Requested worker processes.
Returns
1 on success, 0 on failure.
Description: This function generates a random prime of a given bit size using the vy_search_prime routine. It initializes the random base and sets up the search parameters. The function also allows for parallel processing of the search using multiple child processes. The generated prime is stored in the provided mpz_t p variable.
Parameters
p The mpz_t variable to store the generated prime number.
bit_size The target bit size of the prime.
cores_num The number of cores to use for parallel processing.
Returns
1 if a prime is found, 0 otherwise.
Definition at line 545 of file iZ_apps.c.
References compute_max_vx(), log_error(), MAX, and vy_search_prime().