iZ-Library: src/toolkit/iZ_toolkit.c File Reference
iZ_toolkit.c File Reference
Toolkit (iZ/iZm)
Implementation of iZ index space helpers and iZm/VX segment machinery.
#include <iZ_api.h>
Functions
uint64_t iZ (uint64_t x, int i)
Computes 6x + i for a given x and i.
void iZ_mpz (mpz_t z, mpz_t x, int i)
Computes 6x + i for arbitrary precision values using GMP.
static int compute_k_vx (IZM *iZm)
Count how many small primes (>3) divide vx.
void iZm_construct_vx_base (uint64_t vx, BITMAP *base_x5, BITMAP *base_x7)
Build pre-sieved base bitmaps for a VX segment.
static int vx_set_base_values (VX_SEG *vx_obj, char *y_str)
Initialize mpz-dependent base fields for a VX segment object.
static void vx_det_sieve (IZM *iZm, VX_SEG *vx_obj)
Deterministic phase: mark composites using root primes.
static void vx_prob_sieve (VX_SEG *vx_obj)
Perform probabilistic sieve cleanup for large numeric ranges.
IZM_RANGE_INFO range_info_init (INPUT_SIEVE_RANGE *input_range, int vx)
Map a decimal range input into iZm coordinates and segment bounds.
void range_info_free (IZM_RANGE_INFO *info)
Clear all GMP fields owned by info.
iZ Mapping Helpers
void process_iZ_bitmaps (UI64_ARRAY *primes, BITMAP *x5, BITMAP *x7, uint64_t x_limit)
Traverse iZ bitmaps, emit surviving primes, and mark composites.
void get_root_primes (UI64_ARRAY *primes, uint64_t limit)
Generate primes up to limit for deterministic sieving.
int check_primality (mpz_t n, int rounds)
Check the primality of a number using GMP's probabilistic test.
IZM Lifecycle
IZM * iZm_init (size_t vx)
Allocate and initialize an IZM object for a given VX.
IZM * iZm_clone (IZM *src)
Deep-copy an IZM object for per-worker ownership.
void iZm_free (IZM **iZm)
Release an IZM object and set the caller pointer to NULL.
VX Selection Helpers
uint64_t compute_vx_k (int k)
Calculate VX_{ k }.
uint64_t compute_l2_vx (uint64_t n)
Choose VX using an L2-cache-aware heuristic.
void compute_max_vx (mpz_t vx, int bit_size)
Compute largest VX below 2^bit_size.
Modular Hit Solvers
uint64_t iZm_solve_for_x0 (int m_id, uint64_t p, uint64_t vx, uint64_t y)
Solve first x-hit of prime p for line m_id in segment y.
uint64_t iZm_solve_for_x0_mpz (int m_id, uint64_t p, uint64_t vx, mpz_t y)
GMP variant of iZm_solve_for_x0() for very large y.
int64_t iZm_solve_for_y0 (int m_id, uint64_t p, uint64_t vx, uint64_t x)
Solve first y-hit for fixed x in vertical (vy) scanning.
VX Segment Lifecycle and Execution
VX_SEG * vx_init (IZM *iZm, int start_x, int end_x, char *y_str, int mr_rounds)
Initialize and deterministically sieve one VX segment.
void vx_free (VX_SEG **vx_obj)
Free a VX segment and all owned resources.
void vx_collect_p_gaps (VX_SEG *vx_obj)
Extract prime-gap encoding from a fully sieved segment.
void vx_full_sieve (VX_SEG *vx_obj, int collect_p_gaps)
Complete segment processing (probabilistic stage and optional gaps).
void vx_stream (VX_SEG *vx_obj, FILE *output)
Stream segment primes to an output stream.
Random Prime Search Routines
int vx_search_prime (mpz_t p, int m_id, int vx, int bit_size)
Horizontal iZm/VX random-prime search.
int vy_search_prime (mpz_t p, int m_id, mpz_t vx)
Vertical iZm/VY random-prime search.
Variables
static const int s_primes []
static int s_primes_count = sizeof(s_primes) / sizeof(int)
Detailed Description
Implementation of iZ index space helpers and iZm/VX segment machinery.
Definition in file iZ_toolkit.c.
Function Documentation
compute_k_vx()
int compute_k_vx (IZM * iZm) static
Count how many small primes (>3) divide vx.
Parameters
iZm Initialized toolkit context.
Returns
Number of pre-sieved small primes encoded in vx.
Definition at line 52 of file iZ_toolkit.c.
References s_primes, and IZM::vx.
Referenced by iZm_init().
vx_det_sieve()
void vx_det_sieve (IZM * iZm, VX_SEG * vx_obj) static
Deterministic phase: mark composites using root primes.
Parameters
iZm Toolkit context containing root-prime table and base bitmaps.
vx_obj Segment object to update.
Definition at line 566 of file iZ_toolkit.c.
References UI64_ARRAY::array, VX_SEG::bit_ops, bitmap_clear_steps_simd(), bitmap_get_bit(), UI64_ARRAY::count, VX_SEG::end_x, VX_SEG::is_large_limit, iZm_solve_for_x0(), iZm_solve_for_x0_mpz(), IZM::k_vx, VX_SEG::p_count, VX_SEG::root_limit, IZM::root_primes, VX_SEG::start_x, VX_SEG::vx, VX_SEG::x5, VX_SEG::x7, and VX_SEG::y.
Referenced by vx_init().
vx_prob_sieve()
void vx_prob_sieve (VX_SEG * vx_obj) static
Perform probabilistic sieve cleanup for large numeric ranges.
Parameters
vx_obj Segment object containing deterministic survivors.
Definition at line 633 of file iZ_toolkit.c.
References bitmap_clear_bit(), bitmap_get_bit(), check_primality(), VX_SEG::end_x, VX_SEG::is_large_limit, iZ_mpz(), log_info(), VX_SEG::mr_rounds, VX_SEG::p_count, VX_SEG::p_test_ops, VX_SEG::start_x, VX_SEG::x5, VX_SEG::x7, and VX_SEG::yvx.
Referenced by vx_full_sieve().
vx_set_base_values()
int vx_set_base_values (VX_SEG * vx_obj, char * y_str) static
Initialize mpz-dependent base fields for a VX segment object.
Parameters
vx_obj Segment object to populate.
y_str Decimal y-coordinate for the segment.
Returns
1 on success, 0 on parse/initialization failure.
Definition at line 529 of file iZ_toolkit.c.
References VX_SEG::is_large_limit, iZ_mpz(), log_error(), VX_SEG::root_limit, VX_SEG::vx, VX_SEG::y, and VX_SEG::yvx.
Referenced by vx_init().
Variable Documentation
s_primes
const int s_primes[] static
Initial value:
= {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41,
     43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97}
Small primes used to compute and construct wheel structures.
Definition at line 10 of file iZ_toolkit.c.
Referenced by compute_k_vx(), compute_l2_vx(), compute_vx_k(), and iZm_construct_vx_base().
s_primes_count
int s_primes_count = sizeof(s_primes) / sizeof(int) static
Number of entries available in s_primes.
Definition at line 13 of file iZ_toolkit.c.
Referenced by iZm_construct_vx_base().